// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'asset.dart';

const DeepCollectionEquality _bookmarkAssetPageResultsEquality = DeepCollectionEquality();
final class _BookmarkAssetCopyWithUnset {
  const _BookmarkAssetCopyWithUnset();
}

const _bookmarkAssetCopyWithUnset = _BookmarkAssetCopyWithUnset();

mixin _$BookmarkAsset implements Serializable {
  @override
  String toString() {
    final self = this as BookmarkAsset;
    return 'BookmarkAsset('
        'id: ${self.id}, '
        'bookmark: ${self.bookmark}, '
        'dateCreated: ${self.dateCreated}, '
        'fileSize: ${self.fileSize}, '
        'assetType: ${self.assetType}, '
        'contentType: ${self.contentType}, '
        'displayName: ${self.displayName}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BookmarkAsset;
    return identical(this, other) ||
        other is BookmarkAsset &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.bookmark == self.bookmark &&
            other.dateCreated == self.dateCreated &&
            other.fileSize == self.fileSize &&
            other.assetType == self.assetType &&
            other.contentType == self.contentType &&
            other.displayName == self.displayName &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as BookmarkAsset;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.bookmark,
      self.dateCreated,
      self.fileSize,
      self.assetType,
      self.contentType,
      self.displayName,
      self.status,
    ]);
  }

  /// Creates a copy of this `BookmarkAsset` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = bookmarkAsset.copyWith(id: 1);
  /// final cleared = bookmarkAsset.copyWith(fileSize: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$BookmarkAssetCopyWith<BookmarkAsset> get copyWith => _$BookmarkAssetCopyWithImpl<BookmarkAsset>(this as BookmarkAsset, (value) => value);

  Map<String, Object?> serialize() =>
      _$BookmarkAssetSerialize(this as BookmarkAsset);

  Map<String, Object?> toJson() => serialize();
}

mixin _$BookmarkAssetPage implements Serializable {
  @override
  String toString() {
    final self = this as BookmarkAssetPage;
    return 'BookmarkAssetPage('
        'count: ${self.count}, '
        'next: ${self.next}, '
        'previous: ${self.previous}, '
        'results: ${self.results}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BookmarkAssetPage;
    return identical(this, other) ||
        other is BookmarkAssetPage &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.next == self.next &&
            other.previous == self.previous &&
            _bookmarkAssetPageResultsEquality.equals(other.results, self.results);
  }

  @override
  int get hashCode {
    final self = this as BookmarkAssetPage;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.next,
      self.previous,
      _bookmarkAssetPageResultsEquality.hash(self.results),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$BookmarkAssetPageSerialize(this as BookmarkAssetPage);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$BookmarkAssetCopyWith<$Res> {
  $Res call({
    int? id,
    int? bookmark,
    DateTime? dateCreated,
    int? fileSize,
    String? assetType,
    String? contentType,
    String? displayName,
    String? status,
  });
}

/// @nodoc
final class _$BookmarkAssetCopyWithImpl<$Res> implements _$BookmarkAssetCopyWith<$Res> {
  const _$BookmarkAssetCopyWithImpl(this._self, this._then);

  final BookmarkAsset _self;
  final $Res Function(BookmarkAsset) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? bookmark = null,
    Object? dateCreated = null,
    Object? fileSize = _bookmarkAssetCopyWithUnset,
    Object? assetType = null,
    Object? contentType = null,
    Object? displayName = null,
    Object? status = null,
  }) {
    return _then(
      BookmarkAsset(
        id: id == null ? _self.id : id as int,
        bookmark: bookmark == null ? _self.bookmark : bookmark as int,
        dateCreated: dateCreated == null ? _self.dateCreated : dateCreated as DateTime,
        fileSize: identical(fileSize, _bookmarkAssetCopyWithUnset)
            ? _self.fileSize
            : fileSize as int?,
        assetType: assetType == null ? _self.assetType : assetType as String,
        contentType: contentType == null ? _self.contentType : contentType as String,
        displayName: displayName == null ? _self.displayName : displayName as String,
        status: status == null ? _self.status : status as String,
      )
    );
  }
}
final class $BookmarkAssetSerializer implements Serializer<BookmarkAsset, Map<String, Object?>> {
  const $BookmarkAssetSerializer();

  @override
  Map<String, Object?> serialize(BookmarkAsset value) => _$BookmarkAssetSerialize(value);
}
final class $BookmarkAssetDeserializer implements Deserializer<BookmarkAsset, Map<String, Object?>> {
  const $BookmarkAssetDeserializer();

  @override
  BookmarkAsset deserialize(Map<String, Object?> json) => _$BookmarkAssetDeserialize(json);
}
final class $BookmarkAssetPageSerializer implements Serializer<BookmarkAssetPage, Map<String, Object?>> {
  const $BookmarkAssetPageSerializer();

  @override
  Map<String, Object?> serialize(BookmarkAssetPage value) => _$BookmarkAssetPageSerialize(value);
}
final class $BookmarkAssetPageDeserializer implements Deserializer<BookmarkAssetPage, Map<String, Object?>> {
  const $BookmarkAssetPageDeserializer();

  @override
  BookmarkAssetPage deserialize(Map<String, Object?> json) => _$BookmarkAssetPageDeserialize(json);
}

Map<String, Object?> _$BookmarkAssetSerialize(BookmarkAsset instance) {
  return <String, Object?>{
    'id': instance.id,
    'bookmark': instance.bookmark,
    'date_created': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateCreated,
    ),
    'file_size': instance.fileSize,
    'asset_type': instance.assetType,
    'content_type': instance.contentType,
    'display_name': instance.displayName,
    'status': instance.status,
  };
}

Map<String, Object?> _$BookmarkAssetToJson(BookmarkAsset instance) =>
    _$BookmarkAssetSerialize(instance);

// factory BookmarkAsset.fromJson(Map<String, Object?> json) => _$BookmarkAssetFromJson(json);
BookmarkAsset _$BookmarkAssetDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final bookmarkValue = JsonHelper.as<int>(json['bookmark'], 'bookmark', 'int');
  final dateCreatedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_created'],
    'date_created',
  );
  final fileSizeValue = json['file_size'] == null
      ? null
      : JsonHelper.as<int>(json['file_size'], 'file_size', 'int');
  final assetTypeValue = JsonHelper.as<String>(
    json['asset_type'],
    'asset_type',
    'String',
  );
  final contentTypeValue = JsonHelper.as<String>(
    json['content_type'],
    'content_type',
    'String',
  );
  final displayNameValue = JsonHelper.as<String>(
    json['display_name'],
    'display_name',
    'String',
  );
  final statusValue = JsonHelper.as<String>(json['status'], 'status', 'String');

  return BookmarkAsset(
    id: idValue,
    bookmark: bookmarkValue,
    dateCreated: dateCreatedValue,
    fileSize: fileSizeValue,
    assetType: assetTypeValue,
    contentType: contentTypeValue,
    displayName: displayNameValue,
    status: statusValue,
  );
}

BookmarkAsset _$BookmarkAssetFromJson(Map<String, Object?> json) =>
    _$BookmarkAssetDeserialize(json);

Map<String, Object?> _$BookmarkAssetPageSerialize(BookmarkAssetPage instance) {
  return <String, Object?>{
    'count': instance.count,
    'next': instance.next,
    'previous': instance.previous,
    'results': instance.results
        .map((item) => _$BookmarkAssetSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$BookmarkAssetPageToJson(BookmarkAssetPage instance) =>
    _$BookmarkAssetPageSerialize(instance);

// factory BookmarkAssetPage.fromJson(Map<String, Object?> json) => _$BookmarkAssetPageFromJson(json);
BookmarkAssetPage _$BookmarkAssetPageDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final nextValue = json['next'] == null
      ? null
      : JsonHelper.as<String>(json['next'], 'next', 'String');
  final previousValue = json['previous'] == null
      ? null
      : JsonHelper.as<String>(json['previous'], 'previous', 'String');
  final resultsValue = JsonHelper.decodeList(json['results'], 'results',
      (item, itemKey) => _$BookmarkAssetDeserialize(JsonHelper.asMap(item, itemKey)));

  return BookmarkAssetPage(
    count: countValue,
    results: resultsValue,
    next: nextValue,
    previous: previousValue,
  );
}

BookmarkAssetPage _$BookmarkAssetPageFromJson(Map<String, Object?> json) =>
    _$BookmarkAssetPageDeserialize(json);
