// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmark.dart';

const DeepCollectionEquality _bookmarkTagNamesEquality = DeepCollectionEquality();
const DeepCollectionEquality _bookmarkPageResultsEquality = DeepCollectionEquality();
const DeepCollectionEquality _checkResultAutoTagsEquality = DeepCollectionEquality();
final class _BookmarkCopyWithUnset {
  const _BookmarkCopyWithUnset();
}

const _bookmarkCopyWithUnset = _BookmarkCopyWithUnset();

mixin _$Bookmark implements Serializable {
  @override
  String toString() {
    final self = this as Bookmark;
    return 'Bookmark('
        'id: ${self.id}, '
        'url: ${self.url}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'notes: ${self.notes}, '
        'webArchiveSnapshotUrl: ${self.webArchiveSnapshotUrl}, '
        'faviconUrl: ${self.faviconUrl}, '
        'previewImageUrl: ${self.previewImageUrl}, '
        'isArchived: ${self.isArchived}, '
        'unread: ${self.unread}, '
        'shared: ${self.shared}, '
        'tagNames: ${self.tagNames}, '
        'dateAdded: ${self.dateAdded}, '
        'dateModified: ${self.dateModified}, '
        'websiteTitle: ${self.websiteTitle}, '
        'websiteDescription: ${self.websiteDescription}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Bookmark;
    return identical(this, other) ||
        other is Bookmark &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.url == self.url &&
            other.title == self.title &&
            other.description == self.description &&
            other.notes == self.notes &&
            other.webArchiveSnapshotUrl == self.webArchiveSnapshotUrl &&
            other.faviconUrl == self.faviconUrl &&
            other.previewImageUrl == self.previewImageUrl &&
            other.isArchived == self.isArchived &&
            other.unread == self.unread &&
            other.shared == self.shared &&
            _bookmarkTagNamesEquality.equals(other.tagNames, self.tagNames) &&
            other.dateAdded == self.dateAdded &&
            other.dateModified == self.dateModified &&
            other.websiteTitle == self.websiteTitle &&
            other.websiteDescription == self.websiteDescription;
  }

  @override
  int get hashCode {
    final self = this as Bookmark;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.url,
      self.title,
      self.description,
      self.notes,
      self.webArchiveSnapshotUrl,
      self.faviconUrl,
      self.previewImageUrl,
      self.isArchived,
      self.unread,
      self.shared,
      _bookmarkTagNamesEquality.hash(self.tagNames),
      self.dateAdded,
      self.dateModified,
      self.websiteTitle,
      self.websiteDescription,
    ]);
  }

  /// Creates a copy of this `Bookmark` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = bookmark.copyWith(id: 1);
  /// final cleared = bookmark.copyWith(webArchiveSnapshotUrl: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$BookmarkCopyWith<Bookmark> get copyWith => _$BookmarkCopyWithImpl<Bookmark>(this as Bookmark, (value) => value);

  Map<String, Object?> serialize() => _$BookmarkSerialize(this as Bookmark);

  Map<String, Object?> toJson() => serialize();
}

mixin _$BookmarkPage implements Serializable {
  @override
  String toString() {
    final self = this as BookmarkPage;
    return 'BookmarkPage('
        'count: ${self.count}, '
        'next: ${self.next}, '
        'previous: ${self.previous}, '
        'results: ${self.results}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BookmarkPage;
    return identical(this, other) ||
        other is BookmarkPage &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.next == self.next &&
            other.previous == self.previous &&
            _bookmarkPageResultsEquality.equals(other.results, self.results);
  }

  @override
  int get hashCode {
    final self = this as BookmarkPage;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.next,
      self.previous,
      _bookmarkPageResultsEquality.hash(self.results),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$BookmarkPageSerialize(this as BookmarkPage);

  Map<String, Object?> toJson() => serialize();
}

mixin _$WebsiteMetadata implements Serializable {
  @override
  String toString() {
    final self = this as WebsiteMetadata;
    return 'WebsiteMetadata('
        'url: ${self.url}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'previewImage: ${self.previewImage}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as WebsiteMetadata;
    return identical(this, other) ||
        other is WebsiteMetadata &&
            runtimeType == other.runtimeType &&
            other.url == self.url &&
            other.title == self.title &&
            other.description == self.description &&
            other.previewImage == self.previewImage;
  }

  @override
  int get hashCode {
    final self = this as WebsiteMetadata;
    return Object.hashAll([
      runtimeType,
      self.url,
      self.title,
      self.description,
      self.previewImage,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$WebsiteMetadataSerialize(this as WebsiteMetadata);

  Map<String, Object?> toJson() => serialize();
}

mixin _$CheckResult implements Serializable {
  @override
  String toString() {
    final self = this as CheckResult;
    return 'CheckResult('
        'bookmark: ${self.bookmark}, '
        'metadata: ${self.metadata}, '
        'autoTags: ${self.autoTags}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckResult;
    return identical(this, other) ||
        other is CheckResult &&
            runtimeType == other.runtimeType &&
            other.bookmark == self.bookmark &&
            other.metadata == self.metadata &&
            _checkResultAutoTagsEquality.equals(other.autoTags, self.autoTags);
  }

  @override
  int get hashCode {
    final self = this as CheckResult;
    return Object.hashAll([
      runtimeType,
      self.bookmark,
      self.metadata,
      _checkResultAutoTagsEquality.hash(self.autoTags),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$CheckResultSerialize(this as CheckResult);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$BookmarkCopyWith<$Res> {
  $Res call({
    int? id,
    String? url,
    String? title,
    String? description,
    String? notes,
    String? webArchiveSnapshotUrl,
    String? faviconUrl,
    String? previewImageUrl,
    bool? isArchived,
    bool? unread,
    bool? shared,
    List<String>? tagNames,
    DateTime? dateAdded,
    DateTime? dateModified,
    String? websiteTitle,
    String? websiteDescription,
  });
}

/// @nodoc
final class _$BookmarkCopyWithImpl<$Res> implements _$BookmarkCopyWith<$Res> {
  const _$BookmarkCopyWithImpl(this._self, this._then);

  final Bookmark _self;
  final $Res Function(Bookmark) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? url = null,
    Object? title = null,
    Object? description = null,
    Object? notes = null,
    Object? webArchiveSnapshotUrl = _bookmarkCopyWithUnset,
    Object? faviconUrl = _bookmarkCopyWithUnset,
    Object? previewImageUrl = _bookmarkCopyWithUnset,
    Object? isArchived = null,
    Object? unread = null,
    Object? shared = null,
    Object? tagNames = null,
    Object? dateAdded = null,
    Object? dateModified = null,
    Object? websiteTitle = _bookmarkCopyWithUnset,
    Object? websiteDescription = _bookmarkCopyWithUnset,
  }) {
    return _then(
      Bookmark(
        id: id == null ? _self.id : id as int,
        url: url == null ? _self.url : url as String,
        title: title == null ? _self.title : title as String,
        description: description == null ? _self.description : description as String,
        notes: notes == null ? _self.notes : notes as String,
        isArchived: isArchived == null ? _self.isArchived : isArchived as bool,
        unread: unread == null ? _self.unread : unread as bool,
        shared: shared == null ? _self.shared : shared as bool,
        tagNames: tagNames == null ? _self.tagNames : tagNames as List<String>,
        dateAdded: dateAdded == null ? _self.dateAdded : dateAdded as DateTime,
        dateModified: dateModified == null ? _self.dateModified : dateModified as DateTime,
        webArchiveSnapshotUrl: identical(webArchiveSnapshotUrl, _bookmarkCopyWithUnset)
            ? _self.webArchiveSnapshotUrl
            : webArchiveSnapshotUrl as String?,
        faviconUrl: identical(faviconUrl, _bookmarkCopyWithUnset)
            ? _self.faviconUrl
            : faviconUrl as String?,
        previewImageUrl: identical(previewImageUrl, _bookmarkCopyWithUnset)
            ? _self.previewImageUrl
            : previewImageUrl as String?,
        websiteTitle: identical(websiteTitle, _bookmarkCopyWithUnset)
            ? _self.websiteTitle
            : websiteTitle as String?,
        websiteDescription: identical(websiteDescription, _bookmarkCopyWithUnset)
            ? _self.websiteDescription
            : websiteDescription as String?,
      )
    );
  }
}
final class $BookmarkSerializer implements Serializer<Bookmark, Map<String, Object?>> {
  const $BookmarkSerializer();

  @override
  Map<String, Object?> serialize(Bookmark value) => _$BookmarkSerialize(value);
}
final class $BookmarkDeserializer implements Deserializer<Bookmark, Map<String, Object?>> {
  const $BookmarkDeserializer();

  @override
  Bookmark deserialize(Map<String, Object?> json) => _$BookmarkDeserialize(json);
}
final class $BookmarkPageSerializer implements Serializer<BookmarkPage, Map<String, Object?>> {
  const $BookmarkPageSerializer();

  @override
  Map<String, Object?> serialize(BookmarkPage value) => _$BookmarkPageSerialize(value);
}
final class $BookmarkPageDeserializer implements Deserializer<BookmarkPage, Map<String, Object?>> {
  const $BookmarkPageDeserializer();

  @override
  BookmarkPage deserialize(Map<String, Object?> json) => _$BookmarkPageDeserialize(json);
}
final class $WebsiteMetadataSerializer implements Serializer<WebsiteMetadata, Map<String, Object?>> {
  const $WebsiteMetadataSerializer();

  @override
  Map<String, Object?> serialize(WebsiteMetadata value) => _$WebsiteMetadataSerialize(value);
}
final class $WebsiteMetadataDeserializer implements Deserializer<WebsiteMetadata, Map<String, Object?>> {
  const $WebsiteMetadataDeserializer();

  @override
  WebsiteMetadata deserialize(Map<String, Object?> json) => _$WebsiteMetadataDeserialize(json);
}
final class $CheckResultSerializer implements Serializer<CheckResult, Map<String, Object?>> {
  const $CheckResultSerializer();

  @override
  Map<String, Object?> serialize(CheckResult value) => _$CheckResultSerialize(value);
}
final class $CheckResultDeserializer implements Deserializer<CheckResult, Map<String, Object?>> {
  const $CheckResultDeserializer();

  @override
  CheckResult deserialize(Map<String, Object?> json) => _$CheckResultDeserialize(json);
}

Map<String, Object?> _$BookmarkSerialize(Bookmark instance) {
  return <String, Object?>{
    'id': instance.id,
    'url': instance.url,
    'title': instance.title,
    'description': instance.description,
    'notes': instance.notes,
    'web_archive_snapshot_url': instance.webArchiveSnapshotUrl,
    'favicon_url': instance.faviconUrl,
    'preview_image_url': instance.previewImageUrl,
    'is_archived': instance.isArchived,
    'unread': instance.unread,
    'shared': instance.shared,
    'tag_names': instance.tagNames
        .map((item) => item)
        .toList(),
    'date_added': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateAdded,
    ),
    'date_modified': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateModified,
    ),
    'website_title': instance.websiteTitle,
    'website_description': instance.websiteDescription,
  };
}

Map<String, Object?> _$BookmarkToJson(Bookmark instance) =>
    _$BookmarkSerialize(instance);

// factory Bookmark.fromJson(Map<String, Object?> json) => _$BookmarkFromJson(json);
Bookmark _$BookmarkDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final urlValue = JsonHelper.as<String>(json['url'], 'url', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = JsonHelper.as<String>(
    json['description'],
    'description',
    'String',
  );
  final notesValue = JsonHelper.as<String>(json['notes'], 'notes', 'String');
  final webArchiveSnapshotUrlValue = json['web_archive_snapshot_url'] == null
      ? null
      : JsonHelper.as<String>(json['web_archive_snapshot_url'], 'web_archive_snapshot_url', 'String');
  final faviconUrlValue = json['favicon_url'] == null
      ? null
      : JsonHelper.as<String>(json['favicon_url'], 'favicon_url', 'String');
  final previewImageUrlValue = json['preview_image_url'] == null
      ? null
      : JsonHelper.as<String>(json['preview_image_url'], 'preview_image_url', 'String');
  final isArchivedValue = JsonHelper.as<bool>(
    json['is_archived'],
    'is_archived',
    'bool',
  );
  final unreadValue = JsonHelper.as<bool>(json['unread'], 'unread', 'bool');
  final sharedValue = JsonHelper.as<bool>(json['shared'], 'shared', 'bool');
  final tagNamesValue = JsonHelper.decodeList(json['tag_names'], 'tag_names',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));
  final dateAddedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_added'],
    'date_added',
  );
  final dateModifiedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_modified'],
    'date_modified',
  );
  final websiteTitleValue = json['website_title'] == null
      ? null
      : JsonHelper.as<String>(json['website_title'], 'website_title', 'String');
  final websiteDescriptionValue = json['website_description'] == null
      ? null
      : JsonHelper.as<String>(json['website_description'], 'website_description', 'String');

  return Bookmark(
    id: idValue,
    url: urlValue,
    title: titleValue,
    description: descriptionValue,
    notes: notesValue,
    isArchived: isArchivedValue,
    unread: unreadValue,
    shared: sharedValue,
    tagNames: tagNamesValue,
    dateAdded: dateAddedValue,
    dateModified: dateModifiedValue,
    webArchiveSnapshotUrl: webArchiveSnapshotUrlValue,
    faviconUrl: faviconUrlValue,
    previewImageUrl: previewImageUrlValue,
    websiteTitle: websiteTitleValue,
    websiteDescription: websiteDescriptionValue,
  );
}

Bookmark _$BookmarkFromJson(Map<String, Object?> json) =>
    _$BookmarkDeserialize(json);

Map<String, Object?> _$BookmarkPageSerialize(BookmarkPage instance) {
  return <String, Object?>{
    'count': instance.count,
    'next': instance.next,
    'previous': instance.previous,
    'results': instance.results
        .map((item) => _$BookmarkSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$BookmarkPageToJson(BookmarkPage instance) =>
    _$BookmarkPageSerialize(instance);

// factory BookmarkPage.fromJson(Map<String, Object?> json) => _$BookmarkPageFromJson(json);
BookmarkPage _$BookmarkPageDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final nextValue = json['next'] == null
      ? null
      : JsonHelper.as<String>(json['next'], 'next', 'String');
  final previousValue = json['previous'] == null
      ? null
      : JsonHelper.as<String>(json['previous'], 'previous', 'String');
  final resultsValue = JsonHelper.decodeList(json['results'], 'results',
      (item, itemKey) => _$BookmarkDeserialize(JsonHelper.asMap(item, itemKey)));

  return BookmarkPage(
    count: countValue,
    results: resultsValue,
    next: nextValue,
    previous: previousValue,
  );
}

BookmarkPage _$BookmarkPageFromJson(Map<String, Object?> json) =>
    _$BookmarkPageDeserialize(json);

Map<String, Object?> _$WebsiteMetadataSerialize(WebsiteMetadata instance) {
  return <String, Object?>{
    'url': instance.url,
    'title': instance.title,
    'description': instance.description,
    'preview_image': instance.previewImage,
  };
}

Map<String, Object?> _$WebsiteMetadataToJson(WebsiteMetadata instance) =>
    _$WebsiteMetadataSerialize(instance);

// factory WebsiteMetadata.fromJson(Map<String, Object?> json) => _$WebsiteMetadataFromJson(json);
WebsiteMetadata _$WebsiteMetadataDeserialize(Map<String, Object?> json) {
  final urlValue = json['url'] == null
      ? null
      : JsonHelper.as<String>(json['url'], 'url', 'String');
  final titleValue = json['title'] == null
      ? null
      : JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = json['description'] == null
      ? null
      : JsonHelper.as<String>(json['description'], 'description', 'String');
  final previewImageValue = json['preview_image'] == null
      ? null
      : JsonHelper.as<String>(json['preview_image'], 'preview_image', 'String');

  return WebsiteMetadata(
    url: urlValue,
    title: titleValue,
    description: descriptionValue,
    previewImage: previewImageValue,
  );
}

WebsiteMetadata _$WebsiteMetadataFromJson(Map<String, Object?> json) =>
    _$WebsiteMetadataDeserialize(json);

Map<String, Object?> _$CheckResultSerialize(CheckResult instance) {
  return <String, Object?>{
    'bookmark': instance.bookmark == null
        ? null
        : _$BookmarkSerialize((instance.bookmark!)),
    'metadata': _$WebsiteMetadataSerialize(instance.metadata),
    'auto_tags': instance.autoTags
        .map((item) => item)
        .toList(),
  };
}

Map<String, Object?> _$CheckResultToJson(CheckResult instance) =>
    _$CheckResultSerialize(instance);

// factory CheckResult.fromJson(Map<String, Object?> json) => _$CheckResultFromJson(json);
CheckResult _$CheckResultDeserialize(Map<String, Object?> json) {
  final bookmarkValue = json['bookmark'] == null
      ? null
      : _$BookmarkDeserialize(JsonHelper.asMap(json['bookmark'], 'bookmark'));
  final metadataValue = _$WebsiteMetadataDeserialize(
    JsonHelper.asMap(json['metadata'], 'metadata'),
  );
  final autoTagsValue = JsonHelper.decodeList(json['auto_tags'], 'auto_tags',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));

  return CheckResult(
    metadata: metadataValue,
    autoTags: autoTagsValue,
    bookmark: bookmarkValue,
  );
}

CheckResult _$CheckResultFromJson(Map<String, Object?> json) =>
    _$CheckResultDeserialize(json);
