// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bundle.dart';

const DeepCollectionEquality _bundlePageResultsEquality = DeepCollectionEquality();

mixin _$Bundle implements Serializable {
  @override
  String toString() {
    final self = this as Bundle;
    return 'Bundle('
        'id: ${self.id}, '
        'name: ${self.name}, '
        'search: ${self.search}, '
        'anyTags: ${self.anyTags}, '
        'allTags: ${self.allTags}, '
        'excludedTags: ${self.excludedTags}, '
        'filterUnread: ${self.filterUnread}, '
        'filterShared: ${self.filterShared}, '
        'order: ${self.order}, '
        'dateCreated: ${self.dateCreated}, '
        'dateModified: ${self.dateModified}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Bundle;
    return identical(this, other) ||
        other is Bundle &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.name == self.name &&
            other.search == self.search &&
            other.anyTags == self.anyTags &&
            other.allTags == self.allTags &&
            other.excludedTags == self.excludedTags &&
            other.filterUnread == self.filterUnread &&
            other.filterShared == self.filterShared &&
            other.order == self.order &&
            other.dateCreated == self.dateCreated &&
            other.dateModified == self.dateModified;
  }

  @override
  int get hashCode {
    final self = this as Bundle;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.name,
      self.search,
      self.anyTags,
      self.allTags,
      self.excludedTags,
      self.filterUnread,
      self.filterShared,
      self.order,
      self.dateCreated,
      self.dateModified,
    ]);
  }

  /// Creates a copy of this `Bundle` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = bundle.copyWith(id: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$BundleCopyWith<Bundle> get copyWith => _$BundleCopyWithImpl<Bundle>(this as Bundle, (value) => value);

  Map<String, Object?> serialize() => _$BundleSerialize(this as Bundle);

  Map<String, Object?> toJson() => serialize();
}

mixin _$BundlePage implements Serializable {
  @override
  String toString() {
    final self = this as BundlePage;
    return 'BundlePage('
        'count: ${self.count}, '
        'next: ${self.next}, '
        'previous: ${self.previous}, '
        'results: ${self.results}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BundlePage;
    return identical(this, other) ||
        other is BundlePage &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.next == self.next &&
            other.previous == self.previous &&
            _bundlePageResultsEquality.equals(other.results, self.results);
  }

  @override
  int get hashCode {
    final self = this as BundlePage;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.next,
      self.previous,
      _bundlePageResultsEquality.hash(self.results),
    ]);
  }

  Map<String, Object?> serialize() => _$BundlePageSerialize(this as BundlePage);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$BundleCopyWith<$Res> {
  $Res call({
    int? id,
    String? name,
    String? search,
    String? anyTags,
    String? allTags,
    String? excludedTags,
    String? filterUnread,
    String? filterShared,
    int? order,
    DateTime? dateCreated,
    DateTime? dateModified,
  });
}

/// @nodoc
final class _$BundleCopyWithImpl<$Res> implements _$BundleCopyWith<$Res> {
  const _$BundleCopyWithImpl(this._self, this._then);

  final Bundle _self;
  final $Res Function(Bundle) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? name = null,
    Object? search = null,
    Object? anyTags = null,
    Object? allTags = null,
    Object? excludedTags = null,
    Object? filterUnread = null,
    Object? filterShared = null,
    Object? order = null,
    Object? dateCreated = null,
    Object? dateModified = null,
  }) {
    return _then(
      Bundle(
        id: id == null ? _self.id : id as int,
        name: name == null ? _self.name : name as String,
        search: search == null ? _self.search : search as String,
        anyTags: anyTags == null ? _self.anyTags : anyTags as String,
        allTags: allTags == null ? _self.allTags : allTags as String,
        excludedTags: excludedTags == null ? _self.excludedTags : excludedTags as String,
        filterUnread: filterUnread == null ? _self.filterUnread : filterUnread as String,
        filterShared: filterShared == null ? _self.filterShared : filterShared as String,
        order: order == null ? _self.order : order as int,
        dateCreated: dateCreated == null ? _self.dateCreated : dateCreated as DateTime,
        dateModified: dateModified == null ? _self.dateModified : dateModified as DateTime,
      )
    );
  }
}
final class $BundleSerializer implements Serializer<Bundle, Map<String, Object?>> {
  const $BundleSerializer();

  @override
  Map<String, Object?> serialize(Bundle value) => _$BundleSerialize(value);
}
final class $BundleDeserializer implements Deserializer<Bundle, Map<String, Object?>> {
  const $BundleDeserializer();

  @override
  Bundle deserialize(Map<String, Object?> json) => _$BundleDeserialize(json);
}
final class $BundlePageSerializer implements Serializer<BundlePage, Map<String, Object?>> {
  const $BundlePageSerializer();

  @override
  Map<String, Object?> serialize(BundlePage value) => _$BundlePageSerialize(value);
}
final class $BundlePageDeserializer implements Deserializer<BundlePage, Map<String, Object?>> {
  const $BundlePageDeserializer();

  @override
  BundlePage deserialize(Map<String, Object?> json) => _$BundlePageDeserialize(json);
}

Map<String, Object?> _$BundleSerialize(Bundle instance) {
  return <String, Object?>{
    'id': instance.id,
    'name': instance.name,
    'search': instance.search,
    'any_tags': instance.anyTags,
    'all_tags': instance.allTags,
    'excluded_tags': instance.excludedTags,
    'filter_unread': instance.filterUnread,
    'filter_shared': instance.filterShared,
    'order': instance.order,
    'date_created': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateCreated,
    ),
    'date_modified': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateModified,
    ),
  };
}

Map<String, Object?> _$BundleToJson(Bundle instance) =>
    _$BundleSerialize(instance);

// factory Bundle.fromJson(Map<String, Object?> json) => _$BundleFromJson(json);
Bundle _$BundleDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final searchValue = JsonHelper.as<String>(json['search'], 'search', 'String');
  final anyTagsValue = JsonHelper.as<String>(
    json['any_tags'],
    'any_tags',
    'String',
  );
  final allTagsValue = JsonHelper.as<String>(
    json['all_tags'],
    'all_tags',
    'String',
  );
  final excludedTagsValue = JsonHelper.as<String>(
    json['excluded_tags'],
    'excluded_tags',
    'String',
  );
  final filterUnreadValue = JsonHelper.as<String>(
    json['filter_unread'],
    'filter_unread',
    'String',
  );
  final filterSharedValue = JsonHelper.as<String>(
    json['filter_shared'],
    'filter_shared',
    'String',
  );
  final orderValue = JsonHelper.as<int>(json['order'], 'order', 'int');
  final dateCreatedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_created'],
    'date_created',
  );
  final dateModifiedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_modified'],
    'date_modified',
  );

  return Bundle(
    id: idValue,
    name: nameValue,
    search: searchValue,
    anyTags: anyTagsValue,
    allTags: allTagsValue,
    excludedTags: excludedTagsValue,
    filterUnread: filterUnreadValue,
    filterShared: filterSharedValue,
    order: orderValue,
    dateCreated: dateCreatedValue,
    dateModified: dateModifiedValue,
  );
}

Bundle _$BundleFromJson(Map<String, Object?> json) =>
    _$BundleDeserialize(json);

Map<String, Object?> _$BundlePageSerialize(BundlePage instance) {
  return <String, Object?>{
    'count': instance.count,
    'next': instance.next,
    'previous': instance.previous,
    'results': instance.results
        .map((item) => _$BundleSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$BundlePageToJson(BundlePage instance) =>
    _$BundlePageSerialize(instance);

// factory BundlePage.fromJson(Map<String, Object?> json) => _$BundlePageFromJson(json);
BundlePage _$BundlePageDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final nextValue = json['next'] == null
      ? null
      : JsonHelper.as<String>(json['next'], 'next', 'String');
  final previousValue = json['previous'] == null
      ? null
      : JsonHelper.as<String>(json['previous'], 'previous', 'String');
  final resultsValue = JsonHelper.decodeList(json['results'], 'results',
      (item, itemKey) => _$BundleDeserialize(JsonHelper.asMap(item, itemKey)));

  return BundlePage(
    count: countValue,
    results: resultsValue,
    next: nextValue,
    previous: previousValue,
  );
}

BundlePage _$BundlePageFromJson(Map<String, Object?> json) =>
    _$BundlePageDeserialize(json);
