// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'inputs.dart';

const DeepCollectionEquality _bookmarkInputTagNamesEquality = DeepCollectionEquality();
final class _BundleInputCopyWithUnset {
  const _BundleInputCopyWithUnset();
}

const _bundleInputCopyWithUnset = _BundleInputCopyWithUnset();

mixin _$BookmarkInput implements Serializable {
  @override
  String toString() {
    final self = this as BookmarkInput;
    return 'BookmarkInput('
        'url: ${self.url}, '
        'title: ${self.title}, '
        'description: ${self.description}, '
        'notes: ${self.notes}, '
        'isArchived: ${self.isArchived}, '
        'unread: ${self.unread}, '
        'shared: ${self.shared}, '
        'tagNames: ${self.tagNames}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BookmarkInput;
    return identical(this, other) ||
        other is BookmarkInput &&
            runtimeType == other.runtimeType &&
            other.url == self.url &&
            other.title == self.title &&
            other.description == self.description &&
            other.notes == self.notes &&
            other.isArchived == self.isArchived &&
            other.unread == self.unread &&
            other.shared == self.shared &&
            _bookmarkInputTagNamesEquality.equals(other.tagNames, self.tagNames);
  }

  @override
  int get hashCode {
    final self = this as BookmarkInput;
    return Object.hashAll([
      runtimeType,
      self.url,
      self.title,
      self.description,
      self.notes,
      self.isArchived,
      self.unread,
      self.shared,
      _bookmarkInputTagNamesEquality.hash(self.tagNames),
    ]);
  }

  /// Creates a copy of this `BookmarkInput` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = bookmarkInput.copyWith(url: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$BookmarkInputCopyWith<BookmarkInput> get copyWith => _$BookmarkInputCopyWithImpl<BookmarkInput>(this as BookmarkInput, (value) => value);

  Map<String, Object?> serialize() =>
      _$BookmarkInputSerialize(this as BookmarkInput);

  Map<String, Object?> toJson() => serialize();
}

mixin _$TagInput implements Serializable {
  @override
  String toString() {
    final self = this as TagInput;
    return 'TagInput('
        'name: ${self.name}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TagInput;
    return identical(this, other) ||
        other is TagInput &&
            runtimeType == other.runtimeType &&
            other.name == self.name;
  }

  @override
  int get hashCode {
    final self = this as TagInput;
    return Object.hashAll([
      runtimeType,
      self.name,
    ]);
  }

  Map<String, Object?> serialize() => _$TagInputSerialize(this as TagInput);

  Map<String, Object?> toJson() => serialize();
}

mixin _$BundleInput implements Serializable {
  @override
  String toString() {
    final self = this as BundleInput;
    return 'BundleInput('
        'name: ${self.name}, '
        'search: ${self.search}, '
        'anyTags: ${self.anyTags}, '
        'allTags: ${self.allTags}, '
        'excludedTags: ${self.excludedTags}, '
        'filterUnread: ${self.filterUnread}, '
        'filterShared: ${self.filterShared}, '
        'order: ${self.order}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as BundleInput;
    return identical(this, other) ||
        other is BundleInput &&
            runtimeType == other.runtimeType &&
            other.name == self.name &&
            other.search == self.search &&
            other.anyTags == self.anyTags &&
            other.allTags == self.allTags &&
            other.excludedTags == self.excludedTags &&
            other.filterUnread == self.filterUnread &&
            other.filterShared == self.filterShared &&
            other.order == self.order;
  }

  @override
  int get hashCode {
    final self = this as BundleInput;
    return Object.hashAll([
      runtimeType,
      self.name,
      self.search,
      self.anyTags,
      self.allTags,
      self.excludedTags,
      self.filterUnread,
      self.filterShared,
      self.order,
    ]);
  }

  /// Creates a copy of this `BundleInput` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = bundleInput.copyWith(name: 'John');
  /// final cleared = bundleInput.copyWith(order: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$BundleInputCopyWith<BundleInput> get copyWith => _$BundleInputCopyWithImpl<BundleInput>(this as BundleInput, (value) => value);

  Map<String, Object?> serialize() =>
      _$BundleInputSerialize(this as BundleInput);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$BookmarkInputCopyWith<$Res> {
  $Res call({
    String? url,
    String? title,
    String? description,
    String? notes,
    bool? isArchived,
    bool? unread,
    bool? shared,
    List<String>? tagNames,
  });
}

/// @nodoc
final class _$BookmarkInputCopyWithImpl<$Res> implements _$BookmarkInputCopyWith<$Res> {
  const _$BookmarkInputCopyWithImpl(this._self, this._then);

  final BookmarkInput _self;
  final $Res Function(BookmarkInput) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? url = null,
    Object? title = null,
    Object? description = null,
    Object? notes = null,
    Object? isArchived = null,
    Object? unread = null,
    Object? shared = null,
    Object? tagNames = null,
  }) {
    return _then(
      BookmarkInput(
        url: url == null ? _self.url : url as String,
        title: title == null ? _self.title : title as String,
        description: description == null ? _self.description : description as String,
        notes: notes == null ? _self.notes : notes as String,
        isArchived: isArchived == null ? _self.isArchived : isArchived as bool,
        unread: unread == null ? _self.unread : unread as bool,
        shared: shared == null ? _self.shared : shared as bool,
        tagNames: tagNames == null ? _self.tagNames : tagNames as List<String>,
      )
    );
  }
}
/// @nodoc
abstract class _$BundleInputCopyWith<$Res> {
  $Res call({
    String? name,
    String? search,
    String? anyTags,
    String? allTags,
    String? excludedTags,
    String? filterUnread,
    String? filterShared,
    int? order,
  });
}

/// @nodoc
final class _$BundleInputCopyWithImpl<$Res> implements _$BundleInputCopyWith<$Res> {
  const _$BundleInputCopyWithImpl(this._self, this._then);

  final BundleInput _self;
  final $Res Function(BundleInput) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? name = null,
    Object? search = null,
    Object? anyTags = null,
    Object? allTags = null,
    Object? excludedTags = null,
    Object? filterUnread = null,
    Object? filterShared = null,
    Object? order = _bundleInputCopyWithUnset,
  }) {
    return _then(
      BundleInput(
        name: name == null ? _self.name : name as String,
        search: search == null ? _self.search : search as String,
        anyTags: anyTags == null ? _self.anyTags : anyTags as String,
        allTags: allTags == null ? _self.allTags : allTags as String,
        excludedTags: excludedTags == null ? _self.excludedTags : excludedTags as String,
        filterUnread: filterUnread == null ? _self.filterUnread : filterUnread as String,
        filterShared: filterShared == null ? _self.filterShared : filterShared as String,
        order: identical(order, _bundleInputCopyWithUnset)
            ? _self.order
            : order as int?,
      )
    );
  }
}
final class $BookmarkInputSerializer implements Serializer<BookmarkInput, Map<String, Object?>> {
  const $BookmarkInputSerializer();

  @override
  Map<String, Object?> serialize(BookmarkInput value) => _$BookmarkInputSerialize(value);
}
final class $BookmarkInputDeserializer implements Deserializer<BookmarkInput, Map<String, Object?>> {
  const $BookmarkInputDeserializer();

  @override
  BookmarkInput deserialize(Map<String, Object?> json) => _$BookmarkInputDeserialize(json);
}
final class $TagInputSerializer implements Serializer<TagInput, Map<String, Object?>> {
  const $TagInputSerializer();

  @override
  Map<String, Object?> serialize(TagInput value) => _$TagInputSerialize(value);
}
final class $TagInputDeserializer implements Deserializer<TagInput, Map<String, Object?>> {
  const $TagInputDeserializer();

  @override
  TagInput deserialize(Map<String, Object?> json) => _$TagInputDeserialize(json);
}
final class $BundleInputSerializer implements Serializer<BundleInput, Map<String, Object?>> {
  const $BundleInputSerializer();

  @override
  Map<String, Object?> serialize(BundleInput value) => _$BundleInputSerialize(value);
}
final class $BundleInputDeserializer implements Deserializer<BundleInput, Map<String, Object?>> {
  const $BundleInputDeserializer();

  @override
  BundleInput deserialize(Map<String, Object?> json) => _$BundleInputDeserialize(json);
}

Map<String, Object?> _$BookmarkInputSerialize(BookmarkInput instance) {
  return <String, Object?>{
    'url': instance.url,
    'title': instance.title,
    'description': instance.description,
    'notes': instance.notes,
    'is_archived': instance.isArchived,
    'unread': instance.unread,
    'shared': instance.shared,
    'tag_names': instance.tagNames
        .map((item) => item)
        .toList(),
  };
}

Map<String, Object?> _$BookmarkInputToJson(BookmarkInput instance) =>
    _$BookmarkInputSerialize(instance);

// factory BookmarkInput.fromJson(Map<String, Object?> json) => _$BookmarkInputFromJson(json);
BookmarkInput _$BookmarkInputDeserialize(Map<String, Object?> json) {
  final urlValue = JsonHelper.as<String>(json['url'], 'url', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final descriptionValue = JsonHelper.as<String>(
    json['description'],
    'description',
    'String',
  );
  final notesValue = JsonHelper.as<String>(json['notes'], 'notes', 'String');
  final isArchivedValue = JsonHelper.as<bool>(
    json['is_archived'],
    'is_archived',
    'bool',
  );
  final unreadValue = JsonHelper.as<bool>(json['unread'], 'unread', 'bool');
  final sharedValue = JsonHelper.as<bool>(json['shared'], 'shared', 'bool');
  final tagNamesValue = JsonHelper.decodeList(json['tag_names'], 'tag_names',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));

  return BookmarkInput(
    url: urlValue,
    title: titleValue,
    description: descriptionValue,
    notes: notesValue,
    isArchived: isArchivedValue,
    unread: unreadValue,
    shared: sharedValue,
    tagNames: tagNamesValue,
  );
}

BookmarkInput _$BookmarkInputFromJson(Map<String, Object?> json) =>
    _$BookmarkInputDeserialize(json);

Map<String, Object?> _$TagInputSerialize(TagInput instance) {
  return <String, Object?>{
    'name': instance.name,
  };
}

Map<String, Object?> _$TagInputToJson(TagInput instance) =>
    _$TagInputSerialize(instance);

// factory TagInput.fromJson(Map<String, Object?> json) => _$TagInputFromJson(json);
TagInput _$TagInputDeserialize(Map<String, Object?> json) {
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');

  return TagInput(name: nameValue);
}

TagInput _$TagInputFromJson(Map<String, Object?> json) =>
    _$TagInputDeserialize(json);

Map<String, Object?> _$BundleInputSerialize(BundleInput instance) {
  return <String, Object?>{
    'name': instance.name,
    'search': instance.search,
    'any_tags': instance.anyTags,
    'all_tags': instance.allTags,
    'excluded_tags': instance.excludedTags,
    'filter_unread': instance.filterUnread,
    'filter_shared': instance.filterShared,
    'order': instance.order,
  };
}

Map<String, Object?> _$BundleInputToJson(BundleInput instance) =>
    _$BundleInputSerialize(instance);

// factory BundleInput.fromJson(Map<String, Object?> json) => _$BundleInputFromJson(json);
BundleInput _$BundleInputDeserialize(Map<String, Object?> json) {
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final searchValue = JsonHelper.as<String>(json['search'], 'search', 'String');
  final anyTagsValue = JsonHelper.as<String>(
    json['any_tags'],
    'any_tags',
    'String',
  );
  final allTagsValue = JsonHelper.as<String>(
    json['all_tags'],
    'all_tags',
    'String',
  );
  final excludedTagsValue = JsonHelper.as<String>(
    json['excluded_tags'],
    'excluded_tags',
    'String',
  );
  final filterUnreadValue = JsonHelper.as<String>(
    json['filter_unread'],
    'filter_unread',
    'String',
  );
  final filterSharedValue = JsonHelper.as<String>(
    json['filter_shared'],
    'filter_shared',
    'String',
  );
  final orderValue = json['order'] == null
      ? null
      : JsonHelper.as<int>(json['order'], 'order', 'int');

  return BundleInput(
    name: nameValue,
    search: searchValue,
    anyTags: anyTagsValue,
    allTags: allTagsValue,
    excludedTags: excludedTagsValue,
    filterUnread: filterUnreadValue,
    filterShared: filterSharedValue,
    order: orderValue,
  );
}

BundleInput _$BundleInputFromJson(Map<String, Object?> json) =>
    _$BundleInputDeserialize(json);
