// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'profile.dart';

const DeepCollectionEquality _userProfileSearchPreferencesEquality = DeepCollectionEquality();

mixin _$UserProfile implements Serializable {
  @override
  String toString() {
    final self = this as UserProfile;
    return 'UserProfile('
        'theme: ${self.theme}, '
        'bookmarkDateDisplay: ${self.bookmarkDateDisplay}, '
        'bookmarkLinkTarget: ${self.bookmarkLinkTarget}, '
        'webArchiveIntegration: ${self.webArchiveIntegration}, '
        'tagSearch: ${self.tagSearch}, '
        'enableSharing: ${self.enableSharing}, '
        'enablePublicSharing: ${self.enablePublicSharing}, '
        'enableFavicons: ${self.enableFavicons}, '
        'displayUrl: ${self.displayUrl}, '
        'permanentNotes: ${self.permanentNotes}, '
        'searchPreferences: ${self.searchPreferences}, '
        'version: ${self.version}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as UserProfile;
    return identical(this, other) ||
        other is UserProfile &&
            runtimeType == other.runtimeType &&
            other.theme == self.theme &&
            other.bookmarkDateDisplay == self.bookmarkDateDisplay &&
            other.bookmarkLinkTarget == self.bookmarkLinkTarget &&
            other.webArchiveIntegration == self.webArchiveIntegration &&
            other.tagSearch == self.tagSearch &&
            other.enableSharing == self.enableSharing &&
            other.enablePublicSharing == self.enablePublicSharing &&
            other.enableFavicons == self.enableFavicons &&
            other.displayUrl == self.displayUrl &&
            other.permanentNotes == self.permanentNotes &&
            _userProfileSearchPreferencesEquality.equals(other.searchPreferences, self.searchPreferences) &&
            other.version == self.version;
  }

  @override
  int get hashCode {
    final self = this as UserProfile;
    return Object.hashAll([
      runtimeType,
      self.theme,
      self.bookmarkDateDisplay,
      self.bookmarkLinkTarget,
      self.webArchiveIntegration,
      self.tagSearch,
      self.enableSharing,
      self.enablePublicSharing,
      self.enableFavicons,
      self.displayUrl,
      self.permanentNotes,
      _userProfileSearchPreferencesEquality.hash(self.searchPreferences),
      self.version,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$UserProfileSerialize(this as UserProfile);

  Map<String, Object?> toJson() => serialize();
}

mixin _$Health implements Serializable {
  @override
  String toString() {
    final self = this as Health;
    return 'Health('
        'version: ${self.version}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Health;
    return identical(this, other) ||
        other is Health &&
            runtimeType == other.runtimeType &&
            other.version == self.version &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as Health;
    return Object.hashAll([
      runtimeType,
      self.version,
      self.status,
    ]);
  }

  Map<String, Object?> serialize() => _$HealthSerialize(this as Health);

  Map<String, Object?> toJson() => serialize();
}

final class $UserProfileSerializer implements Serializer<UserProfile, Map<String, Object?>> {
  const $UserProfileSerializer();

  @override
  Map<String, Object?> serialize(UserProfile value) => _$UserProfileSerialize(value);
}
final class $UserProfileDeserializer implements Deserializer<UserProfile, Map<String, Object?>> {
  const $UserProfileDeserializer();

  @override
  UserProfile deserialize(Map<String, Object?> json) => _$UserProfileDeserialize(json);
}
final class $HealthSerializer implements Serializer<Health, Map<String, Object?>> {
  const $HealthSerializer();

  @override
  Map<String, Object?> serialize(Health value) => _$HealthSerialize(value);
}
final class $HealthDeserializer implements Deserializer<Health, Map<String, Object?>> {
  const $HealthDeserializer();

  @override
  Health deserialize(Map<String, Object?> json) => _$HealthDeserialize(json);
}

Map<String, Object?> _$UserProfileSerialize(UserProfile instance) {
  return <String, Object?>{
    'theme': instance.theme,
    'bookmark_date_display': instance.bookmarkDateDisplay,
    'bookmark_link_target': instance.bookmarkLinkTarget,
    'web_archive_integration': instance.webArchiveIntegration,
    'tag_search': instance.tagSearch,
    'enable_sharing': instance.enableSharing,
    'enable_public_sharing': instance.enablePublicSharing,
    'enable_favicons': instance.enableFavicons,
    'display_url': instance.displayUrl,
    'permanent_notes': instance.permanentNotes,
    'search_preferences': instance.searchPreferences
        .map((key, value) => MapEntry(key, value)),
    'version': instance.version,
  };
}

Map<String, Object?> _$UserProfileToJson(UserProfile instance) =>
    _$UserProfileSerialize(instance);

// factory UserProfile.fromJson(Map<String, Object?> json) => _$UserProfileFromJson(json);
UserProfile _$UserProfileDeserialize(Map<String, Object?> json) {
  final themeValue = JsonHelper.as<String>(json['theme'], 'theme', 'String');
  final bookmarkDateDisplayValue = JsonHelper.as<String>(
    json['bookmark_date_display'],
    'bookmark_date_display',
    'String',
  );
  final bookmarkLinkTargetValue = JsonHelper.as<String>(
    json['bookmark_link_target'],
    'bookmark_link_target',
    'String',
  );
  final webArchiveIntegrationValue = JsonHelper.as<String>(
    json['web_archive_integration'],
    'web_archive_integration',
    'String',
  );
  final tagSearchValue = JsonHelper.as<String>(
    json['tag_search'],
    'tag_search',
    'String',
  );
  final enableSharingValue = JsonHelper.as<bool>(
    json['enable_sharing'],
    'enable_sharing',
    'bool',
  );
  final enablePublicSharingValue = JsonHelper.as<bool>(
    json['enable_public_sharing'],
    'enable_public_sharing',
    'bool',
  );
  final enableFaviconsValue = JsonHelper.as<bool>(
    json['enable_favicons'],
    'enable_favicons',
    'bool',
  );
  final displayUrlValue = JsonHelper.as<bool>(
    json['display_url'],
    'display_url',
    'bool',
  );
  final permanentNotesValue = JsonHelper.as<bool>(
    json['permanent_notes'],
    'permanent_notes',
    'bool',
  );
  final searchPreferencesValue = JsonHelper.decodeMap(json['search_preferences'], 'search_preferences',
      (value, valueKey) => JsonHelper.as<String>(value, valueKey, 'String'));
  final versionValue = JsonHelper.as<String>(
    json['version'],
    'version',
    'String',
  );

  return UserProfile(
    theme: themeValue,
    bookmarkDateDisplay: bookmarkDateDisplayValue,
    bookmarkLinkTarget: bookmarkLinkTargetValue,
    webArchiveIntegration: webArchiveIntegrationValue,
    tagSearch: tagSearchValue,
    enableSharing: enableSharingValue,
    enablePublicSharing: enablePublicSharingValue,
    enableFavicons: enableFaviconsValue,
    displayUrl: displayUrlValue,
    permanentNotes: permanentNotesValue,
    searchPreferences: searchPreferencesValue,
    version: versionValue,
  );
}

UserProfile _$UserProfileFromJson(Map<String, Object?> json) =>
    _$UserProfileDeserialize(json);

Map<String, Object?> _$HealthSerialize(Health instance) {
  return <String, Object?>{
    'version': instance.version,
    'status': instance.status,
  };
}

Map<String, Object?> _$HealthToJson(Health instance) =>
    _$HealthSerialize(instance);

// factory Health.fromJson(Map<String, Object?> json) => _$HealthFromJson(json);
Health _$HealthDeserialize(Map<String, Object?> json) {
  final versionValue = JsonHelper.as<String>(
    json['version'],
    'version',
    'String',
  );
  final statusValue = JsonHelper.as<String>(json['status'], 'status', 'String');

  return Health(version: versionValue, status: statusValue);
}

Health _$HealthFromJson(Map<String, Object?> json) =>
    _$HealthDeserialize(json);
