// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tag.dart';

const DeepCollectionEquality _tagPageResultsEquality = DeepCollectionEquality();

mixin _$Tag implements Serializable {
  @override
  String toString() {
    final self = this as Tag;
    return 'Tag('
        'id: ${self.id}, '
        'name: ${self.name}, '
        'dateAdded: ${self.dateAdded}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Tag;
    return identical(this, other) ||
        other is Tag &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.name == self.name &&
            other.dateAdded == self.dateAdded;
  }

  @override
  int get hashCode {
    final self = this as Tag;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.name,
      self.dateAdded,
    ]);
  }

  /// Creates a copy of this `Tag` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = tag.copyWith(id: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$TagCopyWith<Tag> get copyWith => _$TagCopyWithImpl<Tag>(this as Tag, (value) => value);

  Map<String, Object?> serialize() => _$TagSerialize(this as Tag);

  Map<String, Object?> toJson() => serialize();
}

mixin _$TagPage implements Serializable {
  @override
  String toString() {
    final self = this as TagPage;
    return 'TagPage('
        'count: ${self.count}, '
        'next: ${self.next}, '
        'previous: ${self.previous}, '
        'results: ${self.results}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as TagPage;
    return identical(this, other) ||
        other is TagPage &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.next == self.next &&
            other.previous == self.previous &&
            _tagPageResultsEquality.equals(other.results, self.results);
  }

  @override
  int get hashCode {
    final self = this as TagPage;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.next,
      self.previous,
      _tagPageResultsEquality.hash(self.results),
    ]);
  }

  Map<String, Object?> serialize() => _$TagPageSerialize(this as TagPage);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$TagCopyWith<$Res> {
  $Res call({
    int? id,
    String? name,
    DateTime? dateAdded,
  });
}

/// @nodoc
final class _$TagCopyWithImpl<$Res> implements _$TagCopyWith<$Res> {
  const _$TagCopyWithImpl(this._self, this._then);

  final Tag _self;
  final $Res Function(Tag) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? name = null,
    Object? dateAdded = null,
  }) {
    return _then(
      Tag(
        id: id == null ? _self.id : id as int,
        name: name == null ? _self.name : name as String,
        dateAdded: dateAdded == null ? _self.dateAdded : dateAdded as DateTime,
      )
    );
  }
}
final class $TagSerializer implements Serializer<Tag, Map<String, Object?>> {
  const $TagSerializer();

  @override
  Map<String, Object?> serialize(Tag value) => _$TagSerialize(value);
}
final class $TagDeserializer implements Deserializer<Tag, Map<String, Object?>> {
  const $TagDeserializer();

  @override
  Tag deserialize(Map<String, Object?> json) => _$TagDeserialize(json);
}
final class $TagPageSerializer implements Serializer<TagPage, Map<String, Object?>> {
  const $TagPageSerializer();

  @override
  Map<String, Object?> serialize(TagPage value) => _$TagPageSerialize(value);
}
final class $TagPageDeserializer implements Deserializer<TagPage, Map<String, Object?>> {
  const $TagPageDeserializer();

  @override
  TagPage deserialize(Map<String, Object?> json) => _$TagPageDeserialize(json);
}

Map<String, Object?> _$TagSerialize(Tag instance) {
  return <String, Object?>{
    'id': instance.id,
    'name': instance.name,
    'date_added': JsonHelper.encodeWithCodec<DateTime, Object?>(
      drfDateTime,
      instance.dateAdded,
    ),
  };
}

Map<String, Object?> _$TagToJson(Tag instance) =>
    _$TagSerialize(instance);

// factory Tag.fromJson(Map<String, Object?> json) => _$TagFromJson(json);
Tag _$TagDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<int>(json['id'], 'id', 'int');
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final dateAddedValue = JsonHelper.decodeWithCodec<DateTime, Object?>(
    drfDateTime,
    json['date_added'],
    'date_added',
  );

  return Tag(id: idValue, name: nameValue, dateAdded: dateAddedValue);
}

Tag _$TagFromJson(Map<String, Object?> json) =>
    _$TagDeserialize(json);

Map<String, Object?> _$TagPageSerialize(TagPage instance) {
  return <String, Object?>{
    'count': instance.count,
    'next': instance.next,
    'previous': instance.previous,
    'results': instance.results
        .map((item) => _$TagSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$TagPageToJson(TagPage instance) =>
    _$TagPageSerialize(instance);

// factory TagPage.fromJson(Map<String, Object?> json) => _$TagPageFromJson(json);
TagPage _$TagPageDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final nextValue = json['next'] == null
      ? null
      : JsonHelper.as<String>(json['next'], 'next', 'String');
  final previousValue = json['previous'] == null
      ? null
      : JsonHelper.as<String>(json['previous'], 'previous', 'String');
  final resultsValue = JsonHelper.decodeList(json['results'], 'results',
      (item, itemKey) => _$TagDeserialize(JsonHelper.asMap(item, itemKey)));

  return TagPage(
    count: countValue,
    results: resultsValue,
    next: nextValue,
    previous: previousValue,
  );
}

TagPage _$TagPageFromJson(Map<String, Object?> json) =>
    _$TagPageDeserialize(json);
