// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'assets_repo.dart';

final class _$AssetsRepo implements AssetsRepo {
  const _$AssetsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<AssetRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<AssetRow>(
      r'''
SELECT id, date_created, file, file_size, asset_type, content_type,
       display_name, status, gzip, bookmark_id
FROM bookmarks_bookmarkasset WHERE id = $1
''',
      [id],
      const $AssetRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<AssetRow?, SqlxError>> owned(int id, int ownerId) {
    return _db.fetchOptional<AssetRow>(
      r'''
SELECT a.id, a.date_created, a.file, a.file_size, a.asset_type,
       a.content_type, a.display_name, a.status, a.gzip, a.bookmark_id
FROM bookmarks_bookmarkasset a
JOIN bookmarks_bookmark b ON b.id = a.bookmark_id
WHERE a.id = $1 AND b.owner_id = $2
''',
      [id, ownerId],
      const $AssetRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<AssetRow, SqlxError>> insert(DateTime dateCreated, String file, int? fileSize, String assetType, String contentType, String displayName, String status, bool gzip, int bookmarkId) {
    return _db.fetchOne<AssetRow>(
      r'''
INSERT INTO bookmarks_bookmarkasset (
  date_created, file, file_size, asset_type, content_type, display_name,
  status, gzip, bookmark_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, date_created, file, file_size, asset_type, content_type,
          display_name, status, gzip, bookmark_id
''',
      [dateCreated, file, fileSize, assetType, contentType, displayName, status, gzip, bookmarkId],
      const $AssetRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> delete(int id, DateTime now) {
    return _db.execute(
      r'''
WITH gone AS (
  DELETE FROM bookmarks_bookmarkasset WHERE id = $1 RETURNING id, bookmark_id
)
UPDATE bookmarks_bookmark b SET
  date_modified = $2,
  latest_snapshot_id = CASE
    WHEN b.latest_snapshot_id = (SELECT id FROM gone) THEN (
      SELECT a.id FROM bookmarks_bookmarkasset a
      WHERE a.bookmark_id = b.id AND a.asset_type = 'snapshot'
        AND a.status = 'complete' AND a.id <> (SELECT id FROM gone)
      ORDER BY a.date_created DESC
      LIMIT 1)
    ELSE b.latest_snapshot_id
  END
WHERE b.id = (SELECT bookmark_id FROM gone)
''',
      [id, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> touchBookmark(int bookmarkId, DateTime now) {
    return _db.execute(
      r'''UPDATE bookmarks_bookmark SET date_modified = $2 WHERE id = $1''',
      [bookmarkId, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
