// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmarks_repo.dart';

final class _$BookmarksRepo implements BookmarksRepo {
  const _$BookmarksRepo(this._db);

  final Executor _db;

  @override
  Future<Result<BookmarkRow?, SqlxError>> owned(int id, int ownerId) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE id = $1
''',
      [id],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow?, SqlxError>> existing(int ownerId, String normalizedUrl, String url) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark
WHERE owner_id = $1
  AND (url_normalized = $2 OR (url_normalized = '' AND url = $3))
ORDER BY id
LIMIT 1
''',
      [ownerId, normalizedUrl, url],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<bool, SqlxError>> urlTaken(int ownerId, String url, int id) {
    return _db.fetchScalar<bool>(
      r'''
SELECT EXISTS (
  SELECT 1 FROM bookmarks_bookmark
  WHERE owner_id = $1 AND url = $2 AND id <> $3
) AS taken
''',
      [ownerId, url, id],
    );
  }

  @override
  Future<Result<bool, SqlxError>> duplicate(int ownerId, String normalizedUrl, String url, int id) {
    return _db.fetchScalar<bool>(
      r'''
SELECT EXISTS (
  SELECT 1 FROM bookmarks_bookmark
  WHERE owner_id = $1
    AND (url_normalized = $2 OR (url_normalized = '' AND url = $3))
    AND id <> $4
) AS duplicate
''',
      [ownerId, normalizedUrl, url, id],
    );
  }

  @override
  Future<Result<BookmarkRow, SqlxError>> insert(String url, String urlNormalized, String title, String description, String notes, bool unread, bool isArchived, bool shared, DateTime dateAdded, DateTime dateModified, int ownerId) {
    return _db.fetchOne<BookmarkRow>(
      r'''
INSERT INTO bookmarks_bookmark (
  url, url_normalized, title, description, notes, website_title,
  website_description, web_archive_snapshot_url, favicon_file,
  preview_image_file, unread, is_archived, shared, date_added, date_modified,
  date_accessed, owner_id, latest_snapshot_id)
VALUES ($1, $2, $3, $4, $5, NULL, NULL, '', '', '', $6, $7, $8, $9, $10, NULL,
        $11, NULL)
RETURNING id, url, url_normalized, title, description, notes,
          web_archive_snapshot_url, favicon_file, preview_image_file, unread,
          is_archived, shared, date_added, date_modified, date_accessed,
          owner_id, latest_snapshot_id
''',
      [url, urlNormalized, title, description, notes, unread, isArchived, shared, dateAdded, dateModified, ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow, SqlxError>> update(int id, String url, String urlNormalized, String title, String description, String notes, bool unread, bool isArchived, bool shared, DateTime dateAdded, DateTime dateModified) {
    return _db.fetchOne<BookmarkRow>(
      r'''
UPDATE bookmarks_bookmark SET
  url = $2, url_normalized = $3, title = $4, description = $5, notes = $6,
  unread = $7, is_archived = $8, shared = $9, date_added = $10,
  date_modified = $11
WHERE id = $1
RETURNING id, url, url_normalized, title, description, notes,
          web_archive_snapshot_url, favicon_file, preview_image_file, unread,
          is_archived, shared, date_added, date_modified, date_accessed,
          owner_id, latest_snapshot_id
''',
      [id, url, urlNormalized, title, description, notes, unread, isArchived, shared, dateAdded, dateModified],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<FileRow>, SqlxError>> delete(int id, int ownerId) {
    return _db.fetchAll<FileRow>(
      r'''
WITH gone AS (
  DELETE FROM bookmarks_bookmark WHERE id = $1 AND owner_id = $2 RETURNING id
), links AS (
  DELETE FROM bookmarks_bookmark_tags WHERE bookmark_id IN (SELECT id FROM gone)
)
DELETE FROM bookmarks_bookmarkasset
WHERE bookmark_id IN (SELECT id FROM gone)
RETURNING file
''',
      [id, ownerId],
      const $FileRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<BookmarkTagRow>, SqlxError>> tagNames(List<int> bookmarkIds) {
    return _db.fetchAll<BookmarkTagRow>(
      r'''
SELECT bt.bookmark_id, t.id AS tag_id, t.name
FROM bookmarks_bookmark_tags bt JOIN bookmarks_tag t ON t.id = bt.tag_id
WHERE bt.bookmark_id = ANY($1)
ORDER BY t.id
''',
      [bookmarkIds],
      const $BookmarkTagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<AssetRow>, SqlxError>> assets(int bookmarkId) {
    return _db.fetchAll<AssetRow>(
      r'''
SELECT id, date_created, file, file_size, asset_type, content_type,
       display_name, status, gzip, bookmark_id
FROM bookmarks_bookmarkasset WHERE bookmark_id = $1
ORDER BY id
''',
      [bookmarkId],
      const $AssetRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unlinkOtherTags(int bookmarkId, List<int> tagIds) {
    return _db.execute(
      r'''
DELETE FROM bookmarks_bookmark_tags
WHERE bookmark_id = $1 AND NOT (tag_id = ANY($2))
''',
      [bookmarkId, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> linkTags(int bookmarkId, List<int> tagIds) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_bookmark_tags (bookmark_id, tag_id)
SELECT $1, tag_id FROM unnest($2::integer[]) AS tag_id
ON CONFLICT (bookmark_id, tag_id) DO NOTHING
''',
      [bookmarkId, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setArchived(int ownerId, List<int> ids, bool archived, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET is_archived = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, archived, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setUnread(int ownerId, List<int> ids, bool unread, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET unread = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, unread, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setShared(int ownerId, List<int> ids, bool shared, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET shared = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, shared, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setState(int id, int ownerId, bool isArchived, bool unread, bool shared) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET is_archived = $3, unread = $4, shared = $5
WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId, isArchived, unread, shared],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> markRead(int id, int ownerId) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET unread = false WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> touch(int ownerId, List<int> ids, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET date_modified = $3
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<List<IdRow>, SqlxError>> ownedIds(int ownerId, List<int> ids) {
    return _db.fetchAll<IdRow>(
      r'''
SELECT id FROM bookmarks_bookmark WHERE owner_id = $1 AND id = ANY($2)
ORDER BY id
''',
      [ownerId, ids],
      const $IdRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> linkAll(List<int> bookmarkIds, List<int> tagIds) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_bookmark_tags (bookmark_id, tag_id)
SELECT b, t FROM unnest($1::integer[]) AS b, unnest($2::integer[]) AS t
ON CONFLICT (bookmark_id, tag_id) DO NOTHING
''',
      [bookmarkIds, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unlinkAll(List<int> bookmarkIds, List<int> tagIds) {
    return _db.execute(
      r'''
DELETE FROM bookmarks_bookmark_tags
WHERE bookmark_id = ANY($1) AND tag_id = ANY($2)
''',
      [bookmarkIds, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<List<BookmarkRow>, SqlxError>> list(int? ownerId, String list, bool publicOnly, DateTime? modifiedSince, DateTime? addedSince, String unread, String shared, String sort) {
    return _db.fetchAll<BookmarkRow>(
      r'''
SELECT b.id, b.url, b.url_normalized, b.title, b.description, b.notes,
       b.web_archive_snapshot_url, b.favicon_file, b.preview_image_file,
       b.unread, b.is_archived, b.shared, b.date_added, b.date_modified,
       b.date_accessed, b.owner_id, b.latest_snapshot_id
FROM bookmarks_bookmark b
WHERE ($1::integer IS NULL OR b.owner_id = $1)
  AND CASE $2::text
        WHEN 'active' THEN NOT b.is_archived
        WHEN 'archived' THEN b.is_archived
        ELSE b.shared AND EXISTS (
          SELECT 1 FROM bookmarks_userprofile p
          WHERE p.user_id = b.owner_id AND p.enable_sharing
            AND (NOT $3::boolean OR p.enable_public_sharing))
      END
  AND ($4::timestamptz IS NULL OR b.date_modified > $4)
  AND ($5::timestamptz IS NULL OR b.date_added > $5)
  AND ($6::text NOT IN ('yes', 'no') OR b.unread = ($6 = 'yes'))
  AND ($7::text NOT IN ('yes', 'no') OR b.shared = ($7 = 'yes'))
ORDER BY
  CASE WHEN $8::text = 'title_asc' THEN
    CASE WHEN b.title <> '' THEN lower(b.title) ELSE lower(b.url) END END ASC,
  CASE WHEN $8 = 'title_desc' THEN
    CASE WHEN b.title <> '' THEN lower(b.title) ELSE lower(b.url) END END DESC,
  CASE WHEN $8 = 'added_asc' THEN b.date_added END ASC,
  CASE WHEN $8 = 'modified_asc' THEN b.date_modified END ASC,
  CASE WHEN $8 = 'modified_desc' THEN b.date_modified END DESC,
  CASE WHEN $8 NOT IN ('title_asc', 'title_desc', 'added_asc',
                       'modified_asc', 'modified_desc')
       THEN b.date_added END DESC,
  CASE WHEN $8 IN ('title_asc', 'added_asc', 'modified_asc') THEN b.id END ASC,
  b.id DESC
''',
      [ownerId, list, publicOnly, modifiedSince, addedSince, unread, shared, sort],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<BookmarkRow>, SqlxError>> allOwned(int ownerId) {
    return _db.fetchAll<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE owner_id = $1 ORDER BY id
''',
      [ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }
}
