// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bundles_repo.dart';

final class _$BundlesRepo implements BundlesRepo {
  const _$BundlesRepo(this._db);

  final Executor _db;

  @override
  Future<Result<List<BundleRow>, SqlxError>> all(int ownerId) {
    return _db.fetchAll<BundleRow>(
      r'''
SELECT id, name, search, any_tags, all_tags, excluded_tags, filter_unread,
       filter_shared, "order", date_created, date_modified, owner_id
FROM bookmarks_bookmarkbundle WHERE owner_id = $1
ORDER BY "order", id
''',
      [ownerId],
      const $BundleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<BundleRow>, SqlxError>> page(
    int ownerId,
    int limit,
    int offset,
  ) {
    return _db.fetchAll<BundleRow>(
      r'''
SELECT id, name, search, any_tags, all_tags, excluded_tags, filter_unread,
       filter_shared, "order", date_created, date_modified, owner_id
FROM bookmarks_bookmarkbundle WHERE owner_id = $1
ORDER BY "order", id
LIMIT $2 OFFSET $3
''',
      [ownerId, limit, offset],
      const $BundleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> count(int ownerId) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*)::integer FROM bookmarks_bookmarkbundle WHERE owner_id = $1
''',
      [ownerId],
    );
  }

  @override
  Future<Result<BundleRow?, SqlxError>> owned(int id, int ownerId) {
    return _db.fetchOptional<BundleRow>(
      r'''
SELECT id, name, search, any_tags, all_tags, excluded_tags, filter_unread,
       filter_shared, "order", date_created, date_modified, owner_id
FROM bookmarks_bookmarkbundle WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
      const $BundleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> nextOrder(int ownerId) {
    return _db.fetchScalar<int>(
      r'''
SELECT (COALESCE(MAX("order"), -1) + 1)::integer AS next
FROM bookmarks_bookmarkbundle WHERE owner_id = $1
''',
      [ownerId],
    );
  }

  @override
  Future<Result<BundleRow, SqlxError>> insert(
    String name,
    String search,
    String anyTags,
    String allTags,
    String excludedTags,
    int order,
    DateTime now,
    int ownerId,
    String filterShared,
    String filterUnread,
  ) {
    return _db.fetchOne<BundleRow>(
      r'''
INSERT INTO bookmarks_bookmarkbundle (
  name, search, any_tags, all_tags, excluded_tags, "order", date_created,
  date_modified, owner_id, filter_shared, filter_unread)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7, $8, $9, $10)
RETURNING id, name, search, any_tags, all_tags, excluded_tags, filter_unread,
          filter_shared, "order", date_created, date_modified, owner_id
''',
      [
        name,
        search,
        anyTags,
        allTags,
        excludedTags,
        order,
        now,
        ownerId,
        filterShared,
        filterUnread,
      ],
      const $BundleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BundleRow, SqlxError>> update(
    int id,
    String name,
    String search,
    String anyTags,
    String allTags,
    String excludedTags,
    int order,
    DateTime now,
    String filterShared,
    String filterUnread,
  ) {
    return _db.fetchOne<BundleRow>(
      r'''
UPDATE bookmarks_bookmarkbundle SET
  name = $2, search = $3, any_tags = $4, all_tags = $5, excluded_tags = $6,
  "order" = $7, date_modified = $8, filter_shared = $9, filter_unread = $10
WHERE id = $1
RETURNING id, name, search, any_tags, all_tags, excluded_tags, filter_unread,
          filter_shared, "order", date_created, date_modified, owner_id
''',
      [
        id,
        name,
        search,
        anyTags,
        allTags,
        excludedTags,
        order,
        now,
        filterShared,
        filterUnread,
      ],
      const $BundleRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> delete(int id, int ownerId) {
    return _db
        .execute(
          r'''
DELETE FROM bookmarks_bookmarkbundle WHERE id = $1 AND owner_id = $2
''',
          [id, ownerId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> renumber(int ownerId) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_bookmarkbundle b SET "order" = r.position
FROM (
  SELECT id, (row_number() OVER (ORDER BY "order", id) - 1)::integer AS position
  FROM bookmarks_bookmarkbundle WHERE owner_id = $1
) r
WHERE b.id = r.id AND b."order" <> r.position
''',
          [ownerId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> setOrder(int id, int order) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_bookmarkbundle SET "order" = $2 WHERE id = $1
''',
          [id, order],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }
}
