// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'rows.dart';

UserRow _$UserRowFromRow(Row row) {
  return UserRow(
    id: row.read<int>('id'),
    password: row.read<String>('password'),
    isSuperuser: row.readBool('is_superuser'),
    username: row.read<String>('username'),
    firstName: row.read<String>('first_name'),
    lastName: row.read<String>('last_name'),
    email: row.read<String>('email'),
    isStaff: row.readBool('is_staff'),
    isActive: row.readBool('is_active'),
    dateJoined: row.readDateTime('date_joined'),
    lastLogin: row.readDateTimeNullable('last_login'),
  );
}

/// Row deserializer for [UserRow].
final class $UserRowRowDeserializer implements RowDeserializer<UserRow> {
  const $UserRowRowDeserializer();

  @override
  UserRow deserialize(Row row) => _$UserRowFromRow(row);
}

/// Typed row query terminals for [UserRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $UserRowQuery on QueryAs<UserRow> {
  /// Fetches exactly one row.
  Future<Result<UserRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$UserRowFromRow);

  /// Fetches zero or one row.
  Future<Result<UserRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$UserRowFromRow);

  /// Fetches every row.
  Future<Result<List<UserRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$UserRowFromRow);
}

ProfileRow _$ProfileRowFromRow(Row row) {
  return ProfileRow(
    id: row.read<int>('id'),
    userId: row.read<int>('user_id'),
    theme: row.read<String>('theme'),
    bookmarkDateDisplay: row.read<String>('bookmark_date_display'),
    bookmarkDescriptionDisplay: row.read<String>('bookmark_description_display'),
    bookmarkDescriptionMaxLines: row.read<int>('bookmark_description_max_lines'),
    bookmarkLinkTarget: row.read<String>('bookmark_link_target'),
    webArchiveIntegration: row.read<String>('web_archive_integration'),
    tagSearch: row.read<String>('tag_search'),
    tagGrouping: row.read<String>('tag_grouping'),
    enableSharing: row.readBool('enable_sharing'),
    enablePublicSharing: row.readBool('enable_public_sharing'),
    enableFavicons: row.readBool('enable_favicons'),
    enablePreviewImages: row.readBool('enable_preview_images'),
    displayUrl: row.readBool('display_url'),
    displayViewBookmarkAction: row.readBool('display_view_bookmark_action'),
    displayEditBookmarkAction: row.readBool('display_edit_bookmark_action'),
    displayArchiveBookmarkAction: row.readBool('display_archive_bookmark_action'),
    displayRemoveBookmarkAction: row.readBool('display_remove_bookmark_action'),
    permanentNotes: row.readBool('permanent_notes'),
    customCss: row.read<String>('custom_css'),
    customCssHash: row.read<String>('custom_css_hash'),
    autoTaggingRules: row.read<String>('auto_tagging_rules'),
    searchPreferencesJson: row.read<String>('search_preferences_json'),
    enableAutomaticHtmlSnapshots: row.readBool('enable_automatic_html_snapshots'),
    defaultMarkUnread: row.readBool('default_mark_unread'),
    defaultMarkShared: row.readBool('default_mark_shared'),
    itemsPerPage: row.read<int>('items_per_page'),
    stickyPagination: row.readBool('sticky_pagination'),
    collapseSidePanel: row.readBool('collapse_side_panel'),
    hideBundles: row.readBool('hide_bundles'),
    legacySearch: row.readBool('legacy_search'),
  );
}

/// Row deserializer for [ProfileRow].
final class $ProfileRowRowDeserializer implements RowDeserializer<ProfileRow> {
  const $ProfileRowRowDeserializer();

  @override
  ProfileRow deserialize(Row row) => _$ProfileRowFromRow(row);
}

/// Typed row query terminals for [ProfileRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ProfileRowQuery on QueryAs<ProfileRow> {
  /// Fetches exactly one row.
  Future<Result<ProfileRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ProfileRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ProfileRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ProfileRowFromRow);

  /// Fetches every row.
  Future<Result<List<ProfileRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ProfileRowFromRow);
}

BookmarkRow _$BookmarkRowFromRow(Row row) {
  return BookmarkRow(
    id: row.read<int>('id'),
    url: row.read<String>('url'),
    urlNormalized: row.read<String>('url_normalized'),
    title: row.read<String>('title'),
    description: row.read<String>('description'),
    notes: row.read<String>('notes'),
    webArchiveSnapshotUrl: row.read<String>('web_archive_snapshot_url'),
    faviconFile: row.read<String>('favicon_file'),
    previewImageFile: row.read<String>('preview_image_file'),
    unread: row.readBool('unread'),
    isArchived: row.readBool('is_archived'),
    shared: row.readBool('shared'),
    dateAdded: row.readDateTime('date_added'),
    dateModified: row.readDateTime('date_modified'),
    ownerId: row.read<int>('owner_id'),
    dateAccessed: row.readDateTimeNullable('date_accessed'),
    latestSnapshotId: row.readNullable<int>('latest_snapshot_id'),
  );
}

/// Row deserializer for [BookmarkRow].
final class $BookmarkRowRowDeserializer implements RowDeserializer<BookmarkRow> {
  const $BookmarkRowRowDeserializer();

  @override
  BookmarkRow deserialize(Row row) => _$BookmarkRowFromRow(row);
}

/// Typed row query terminals for [BookmarkRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BookmarkRowQuery on QueryAs<BookmarkRow> {
  /// Fetches exactly one row.
  Future<Result<BookmarkRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BookmarkRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BookmarkRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BookmarkRowFromRow);

  /// Fetches every row.
  Future<Result<List<BookmarkRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BookmarkRowFromRow);
}

BookmarkTagRow _$BookmarkTagRowFromRow(Row row) {
  return BookmarkTagRow(
    bookmarkId: row.read<int>('bookmark_id'),
    name: row.read<String>('name'),
  );
}

/// Row deserializer for [BookmarkTagRow].
final class $BookmarkTagRowRowDeserializer implements RowDeserializer<BookmarkTagRow> {
  const $BookmarkTagRowRowDeserializer();

  @override
  BookmarkTagRow deserialize(Row row) => _$BookmarkTagRowFromRow(row);
}

/// Typed row query terminals for [BookmarkTagRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BookmarkTagRowQuery on QueryAs<BookmarkTagRow> {
  /// Fetches exactly one row.
  Future<Result<BookmarkTagRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BookmarkTagRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BookmarkTagRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BookmarkTagRowFromRow);

  /// Fetches every row.
  Future<Result<List<BookmarkTagRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BookmarkTagRowFromRow);
}

TagRow _$TagRowFromRow(Row row) {
  return TagRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    dateAdded: row.readDateTime('date_added'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [TagRow].
final class $TagRowRowDeserializer implements RowDeserializer<TagRow> {
  const $TagRowRowDeserializer();

  @override
  TagRow deserialize(Row row) => _$TagRowFromRow(row);
}

/// Typed row query terminals for [TagRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $TagRowQuery on QueryAs<TagRow> {
  /// Fetches exactly one row.
  Future<Result<TagRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$TagRowFromRow);

  /// Fetches zero or one row.
  Future<Result<TagRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$TagRowFromRow);

  /// Fetches every row.
  Future<Result<List<TagRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$TagRowFromRow);
}

TagUsageRow _$TagUsageRowFromRow(Row row) {
  return TagUsageRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    dateAdded: row.readDateTime('date_added'),
    bookmarkCount: row.read<int>('bookmark_count'),
  );
}

/// Row deserializer for [TagUsageRow].
final class $TagUsageRowRowDeserializer implements RowDeserializer<TagUsageRow> {
  const $TagUsageRowRowDeserializer();

  @override
  TagUsageRow deserialize(Row row) => _$TagUsageRowFromRow(row);
}

/// Typed row query terminals for [TagUsageRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $TagUsageRowQuery on QueryAs<TagUsageRow> {
  /// Fetches exactly one row.
  Future<Result<TagUsageRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$TagUsageRowFromRow);

  /// Fetches zero or one row.
  Future<Result<TagUsageRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$TagUsageRowFromRow);

  /// Fetches every row.
  Future<Result<List<TagUsageRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$TagUsageRowFromRow);
}

BundleRow _$BundleRowFromRow(Row row) {
  return BundleRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    search: row.read<String>('search'),
    anyTags: row.read<String>('any_tags'),
    allTags: row.read<String>('all_tags'),
    excludedTags: row.read<String>('excluded_tags'),
    filterUnread: row.read<String>('filter_unread'),
    filterShared: row.read<String>('filter_shared'),
    order: row.read<int>('order'),
    dateCreated: row.readDateTime('date_created'),
    dateModified: row.readDateTime('date_modified'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [BundleRow].
final class $BundleRowRowDeserializer implements RowDeserializer<BundleRow> {
  const $BundleRowRowDeserializer();

  @override
  BundleRow deserialize(Row row) => _$BundleRowFromRow(row);
}

/// Typed row query terminals for [BundleRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BundleRowQuery on QueryAs<BundleRow> {
  /// Fetches exactly one row.
  Future<Result<BundleRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BundleRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BundleRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BundleRowFromRow);

  /// Fetches every row.
  Future<Result<List<BundleRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BundleRowFromRow);
}

ApiTokenRow _$ApiTokenRowFromRow(Row row) {
  return ApiTokenRow(
    id: row.read<int>('id'),
    key: row.read<String>('key'),
    name: row.read<String>('name'),
    created: row.readDateTime('created'),
    userId: row.read<int>('user_id'),
  );
}

/// Row deserializer for [ApiTokenRow].
final class $ApiTokenRowRowDeserializer implements RowDeserializer<ApiTokenRow> {
  const $ApiTokenRowRowDeserializer();

  @override
  ApiTokenRow deserialize(Row row) => _$ApiTokenRowFromRow(row);
}

/// Typed row query terminals for [ApiTokenRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ApiTokenRowQuery on QueryAs<ApiTokenRow> {
  /// Fetches exactly one row.
  Future<Result<ApiTokenRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ApiTokenRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ApiTokenRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ApiTokenRowFromRow);

  /// Fetches every row.
  Future<Result<List<ApiTokenRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ApiTokenRowFromRow);
}

GlobalSettingsRow _$GlobalSettingsRowFromRow(Row row) {
  return GlobalSettingsRow(
    id: row.read<int>('id'),
    landingPage: row.read<String>('landing_page'),
    enableLinkPrefetch: row.readBool('enable_link_prefetch'),
    guestProfileUserId: row.readNullable<int>('guest_profile_user_id'),
  );
}

/// Row deserializer for [GlobalSettingsRow].
final class $GlobalSettingsRowRowDeserializer implements RowDeserializer<GlobalSettingsRow> {
  const $GlobalSettingsRowRowDeserializer();

  @override
  GlobalSettingsRow deserialize(Row row) => _$GlobalSettingsRowFromRow(row);
}

/// Typed row query terminals for [GlobalSettingsRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $GlobalSettingsRowQuery on QueryAs<GlobalSettingsRow> {
  /// Fetches exactly one row.
  Future<Result<GlobalSettingsRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$GlobalSettingsRowFromRow);

  /// Fetches zero or one row.
  Future<Result<GlobalSettingsRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$GlobalSettingsRowFromRow);

  /// Fetches every row.
  Future<Result<List<GlobalSettingsRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$GlobalSettingsRowFromRow);
}

ToastRow _$ToastRowFromRow(Row row) {
  return ToastRow(
    id: row.read<int>('id'),
    key: row.read<String>('key'),
    message: row.read<String>('message'),
    acknowledged: row.readBool('acknowledged'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [ToastRow].
final class $ToastRowRowDeserializer implements RowDeserializer<ToastRow> {
  const $ToastRowRowDeserializer();

  @override
  ToastRow deserialize(Row row) => _$ToastRowFromRow(row);
}

/// Typed row query terminals for [ToastRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ToastRowQuery on QueryAs<ToastRow> {
  /// Fetches exactly one row.
  Future<Result<ToastRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ToastRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ToastRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ToastRowFromRow);

  /// Fetches every row.
  Future<Result<List<ToastRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ToastRowFromRow);
}

IdRow _$IdRowFromRow(Row row) {
  return IdRow(id: row.read<int>('id'));
}

/// Row deserializer for [IdRow].
final class $IdRowRowDeserializer implements RowDeserializer<IdRow> {
  const $IdRowRowDeserializer();

  @override
  IdRow deserialize(Row row) => _$IdRowFromRow(row);
}

/// Typed row query terminals for [IdRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $IdRowQuery on QueryAs<IdRow> {
  /// Fetches exactly one row.
  Future<Result<IdRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$IdRowFromRow);

  /// Fetches zero or one row.
  Future<Result<IdRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$IdRowFromRow);

  /// Fetches every row.
  Future<Result<List<IdRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$IdRowFromRow);
}

FileRow _$FileRowFromRow(Row row) {
  return FileRow(file: row.read<String>('file'));
}

/// Row deserializer for [FileRow].
final class $FileRowRowDeserializer implements RowDeserializer<FileRow> {
  const $FileRowRowDeserializer();

  @override
  FileRow deserialize(Row row) => _$FileRowFromRow(row);
}

/// Typed row query terminals for [FileRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $FileRowQuery on QueryAs<FileRow> {
  /// Fetches exactly one row.
  Future<Result<FileRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$FileRowFromRow);

  /// Fetches zero or one row.
  Future<Result<FileRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$FileRowFromRow);

  /// Fetches every row.
  Future<Result<List<FileRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$FileRowFromRow);
}
