// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'settings_repo.dart';

final class _$SettingsRepo implements SettingsRepo {
  const _$SettingsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<GlobalSettingsRow?, SqlxError>> global() {
    return _db.fetchOptional<GlobalSettingsRow>(
      r'''
SELECT id, landing_page, guest_profile_user_id, enable_link_prefetch
FROM bookmarks_globalsettings ORDER BY id LIMIT 1
''',
      [],
      const $GlobalSettingsRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> ensureGlobal() {
    return _db
        .execute(r'''
INSERT INTO bookmarks_globalsettings (landing_page, guest_profile_user_id,
                                      enable_link_prefetch)
SELECT 'login', NULL, false
WHERE NOT EXISTS (SELECT 1 FROM bookmarks_globalsettings)
''', [])
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> updateGlobal(
    int id,
    String landingPage,
    int? guestProfileUserId,
    bool enableLinkPrefetch,
  ) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_globalsettings SET landing_page = $2,
  guest_profile_user_id = $3, enable_link_prefetch = $4
WHERE id = $1
''',
          [id, landingPage, guestProfileUserId, enableLinkPrefetch],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<List<ToastRow>, SqlxError>> toasts(int ownerId) {
    return _db.fetchAll<ToastRow>(
      r'''
SELECT id, key, message, acknowledged, owner_id FROM bookmarks_toast
WHERE owner_id = $1 AND NOT acknowledged ORDER BY id
''',
      [ownerId],
      const $ToastRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> addToast(
    String key,
    String message,
    int ownerId,
  ) {
    return _db
        .execute(
          r'''
INSERT INTO bookmarks_toast (key, message, acknowledged, owner_id)
VALUES ($1, $2, false, $3)
''',
          [key, message, ownerId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<int?, SqlxError>> acknowledge(int id, int ownerId) {
    return _db.fetchScalar<int?>(
      r'''
UPDATE bookmarks_toast SET acknowledged = true WHERE id = $1 AND owner_id = $2
RETURNING id
''',
      [id, ownerId],
    );
  }

  @override
  Future<Result<Unit, SqlxError>> addMessage(
    String sessionKey,
    String level,
    String message,
    String extraTags,
  ) {
    return _db
        .execute(
          r'''
INSERT INTO clone_message (session_key, level, message, extra_tags)
VALUES ($1, $2, $3, $4)
''',
          [sessionKey, level, message, extraTags],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<List<MessageRow>, SqlxError>> takeMessages(String sessionKey) {
    return _db.fetchAll<MessageRow>(
      r'''
WITH taken AS (
  DELETE FROM clone_message WHERE session_key = $1
  RETURNING id, level, message, extra_tags
)
SELECT level, message, extra_tags FROM taken ORDER BY id
''',
      [sessionKey],
      const $MessageRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setSessionValue(
    String sessionKey,
    String name,
    String value,
  ) {
    return _db
        .execute(
          r'''
INSERT INTO clone_session_value (session_key, name, value) VALUES ($1, $2, $3)
ON CONFLICT (session_key, name) DO UPDATE SET value = EXCLUDED.value
''',
          [sessionKey, name, value],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<String?, SqlxError>> popSessionValue(
    String sessionKey,
    String name,
  ) {
    return _db.fetchScalar<String?>(
      r'''
DELETE FROM clone_session_value WHERE session_key = $1 AND name = $2
RETURNING value
''',
      [sessionKey, name],
    );
  }
}
