// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tags_repo.dart';

final class _$TagsRepo implements TagsRepo {
  const _$TagsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<TagRow?, SqlxError>> named(int ownerId, String name) {
    return _db.fetchOptional<TagRow>(
      r'''
SELECT id, name, date_added, owner_id FROM bookmarks_tag
WHERE owner_id = $1 AND UPPER(name::text) = UPPER($2)
ORDER BY id
LIMIT 1
''',
      [ownerId, name],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<TagRow>, SqlxError>> withNames(int ownerId, List<String> names) {
    return _db.fetchAll<TagRow>(
      r'''
SELECT id, name, date_added, owner_id FROM bookmarks_tag
WHERE owner_id = $1
  AND UPPER(name::text) IN (SELECT UPPER(n) FROM unnest($2::text[]) AS n)
ORDER BY id
''',
      [ownerId, names],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<TagRow>, SqlxError>> sharedNamed(int? ownerId, bool publicOnly, List<String> names) {
    return _db.fetchAll<TagRow>(
      r'''
SELECT DISTINCT t.id, t.name, t.date_added, t.owner_id
FROM bookmarks_tag t
JOIN bookmarks_bookmark_tags bt ON bt.tag_id = t.id
JOIN bookmarks_bookmark b ON b.id = bt.bookmark_id
JOIN bookmarks_userprofile p ON p.user_id = b.owner_id
WHERE b.shared AND p.enable_sharing
  AND (NOT $2::boolean OR p.enable_public_sharing)
  AND ($1::integer IS NULL OR b.owner_id = $1)
  AND UPPER(t.name::text) IN (SELECT UPPER(n) FROM unnest($3::text[]) AS n)
ORDER BY t.id
''',
      [ownerId, publicOnly, names],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<TagRow, SqlxError>> insert(String name, DateTime dateAdded, int ownerId) {
    return _db.fetchOne<TagRow>(
      r'''
INSERT INTO bookmarks_tag (name, date_added, owner_id) VALUES ($1, $2, $3)
RETURNING id, name, date_added, owner_id
''',
      [name, dateAdded, ownerId],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<TagRow?, SqlxError>> owned(int id, int ownerId) {
    return _db.fetchOptional<TagRow>(
      r'''
SELECT id, name, date_added, owner_id FROM bookmarks_tag
WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<TagRow>, SqlxError>> page(int ownerId, int limit, int offset) {
    return _db.fetchAll<TagRow>(
      r'''
SELECT id, name, date_added, owner_id FROM bookmarks_tag
WHERE owner_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
''',
      [ownerId, limit, offset],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> count(int ownerId) {
    return _db.fetchScalar<int>(
      r'''SELECT count(*)::integer FROM bookmarks_tag WHERE owner_id = $1''',
      [ownerId],
    );
  }

  @override
  Future<Result<List<TagRow>, SqlxError>> all(int ownerId) {
    return _db.fetchAll<TagRow>(
      r'''
SELECT id, name, date_added, owner_id FROM bookmarks_tag
WHERE owner_id = $1 ORDER BY id
''',
      [ownerId],
      const $TagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<TagUsageRow>, SqlxError>> listing(int ownerId, String pattern, bool unusedOnly, String sort) {
    return _db.fetchAll<TagUsageRow>(
      r'''
SELECT id, name, date_added, bookmark_count FROM (
  SELECT t.id, t.name, t.date_added,
         (SELECT count(*)::integer FROM bookmarks_bookmark_tags bt
          WHERE bt.tag_id = t.id) AS bookmark_count
  FROM bookmarks_tag t
  WHERE t.owner_id = $1
) t
WHERE ($2 = '' OR UPPER(t.name::text) LIKE UPPER($2))
  AND (NOT $3::boolean OR t.bookmark_count = 0)
ORDER BY
  CASE WHEN $4::text = 'name-desc' THEN t.name END DESC,
  CASE WHEN $4 = 'count-asc' THEN t.bookmark_count END ASC,
  CASE WHEN $4 = 'count-desc' THEN t.bookmark_count END DESC,
  t.name
''',
      [ownerId, pattern, unusedOnly, sort],
      const $TagUsageRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> rename(int id, int ownerId, String name) {
    return _db.execute(
      r'''UPDATE bookmarks_tag SET name = $3 WHERE id = $1 AND owner_id = $2''',
      [id, ownerId, name],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> delete(int id, int ownerId) {
    return _db.execute(
      r'''
WITH gone AS (
  DELETE FROM bookmarks_tag WHERE id = $1 AND owner_id = $2 RETURNING id
)
DELETE FROM bookmarks_bookmark_tags WHERE tag_id IN (SELECT id FROM gone)
''',
      [id, ownerId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> merge(int ownerId, int intoId, List<int> fromIds) {
    return _db.execute(
      r'''
WITH moved AS (
  INSERT INTO bookmarks_bookmark_tags (bookmark_id, tag_id)
  SELECT DISTINCT bt.bookmark_id, $2::integer FROM bookmarks_bookmark_tags bt
  WHERE bt.tag_id = ANY($3)
  ON CONFLICT (bookmark_id, tag_id) DO NOTHING
), unlinked AS (
  DELETE FROM bookmarks_bookmark_tags WHERE tag_id = ANY($3)
)
DELETE FROM bookmarks_tag WHERE owner_id = $1 AND id = ANY($3)
''',
      [ownerId, intoId, fromIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
