// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'users_repo.dart';

UserNameRow _$UserNameRowFromRow(Row row) {
  return UserNameRow(
    id: row.read<int>('id'),
    username: row.read<String>('username'),
  );
}

/// Row deserializer for [UserNameRow].
final class $UserNameRowRowDeserializer
    implements RowDeserializer<UserNameRow> {
  const $UserNameRowRowDeserializer();

  @override
  UserNameRow deserialize(Row row) => _$UserNameRowFromRow(row);
}

/// Typed row query terminals for [UserNameRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $UserNameRowQuery on QueryAs<UserNameRow> {
  /// Fetches exactly one row.
  Future<Result<UserNameRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$UserNameRowFromRow);

  /// Fetches zero or one row.
  Future<Result<UserNameRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$UserNameRowFromRow);

  /// Fetches every row.
  Future<Result<List<UserNameRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$UserNameRowFromRow);
}

final class _$UsersRepo implements UsersRepo {
  const _$UsersRepo(this._db);

  final Executor _db;

  @override
  Future<Result<UserRow?, SqlxError>> byUsername(String username) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, password, last_login, is_superuser, username, first_name,
       last_name, email, is_staff, is_active, date_joined
FROM auth_user WHERE username = $1
''',
      [username],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, password, last_login, is_superuser, username, first_name,
       last_name, email, is_staff, is_active, date_joined
FROM auth_user WHERE id = $1
''',
      [id],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byApiToken(String key) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM bookmarks_apitoken t JOIN auth_user u ON u.id = t.user_id
WHERE t.key = $1
''',
      [key],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> bySession(String key, DateTime now) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM clone_session s JOIN auth_user u ON u.id = s.user_id
WHERE s.session_key = $1 AND s.expire_date > $2
''',
      [key, now],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow, SqlxError>> insert(
    String password,
    bool isSuperuser,
    String username,
    String email,
    DateTime dateJoined,
  ) {
    return _db.fetchOne<UserRow>(
      r'''
INSERT INTO auth_user (password, last_login, is_superuser, username,
                       first_name, last_name, email, is_staff, is_active,
                       date_joined)
VALUES ($1, NULL, $2, $3, '', '', $4, $2, true, $5)
RETURNING id, password, last_login, is_superuser, username, first_name,
          last_name, email, is_staff, is_active, date_joined
''',
      [password, isSuperuser, username, email, dateJoined],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setPassword(int id, String password) {
    return _db
        .execute(
          r'''UPDATE auth_user SET password = $2 WHERE id = $1''',
          [id, password],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> setLastLogin(int id, DateTime at) {
    return _db
        .execute(
          r'''UPDATE auth_user SET last_login = $2 WHERE id = $1''',
          [id, at],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> activeUsers() {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user WHERE is_active ORDER BY username''',
      [],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> allUsers() {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user''',
      [],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> names(List<int> ids) {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user WHERE id = ANY($1) ORDER BY id''',
      [ids],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<ProfileRow?, SqlxError>> profile(int userId) {
    return _db.fetchOptional<ProfileRow>(
      r'''
SELECT id, user_id, theme, bookmark_date_display, bookmark_description_display,
       bookmark_description_max_lines, bookmark_link_target,
       web_archive_integration, tag_search, tag_grouping, enable_sharing,
       enable_public_sharing, enable_favicons, enable_preview_images,
       display_url, display_view_bookmark_action, display_edit_bookmark_action,
       display_archive_bookmark_action, display_remove_bookmark_action,
       permanent_notes, custom_css, custom_css_hash, auto_tagging_rules,
       search_preferences::text AS search_preferences_json,
       enable_automatic_html_snapshots, default_mark_unread,
       default_mark_shared, items_per_page, sticky_pagination,
       collapse_side_panel, hide_bundles, legacy_search
FROM bookmarks_userprofile WHERE user_id = $1
''',
      [userId],
      const $ProfileRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> insertDefaultProfile(int userId) {
    return _db
        .execute(
          r'''
INSERT INTO bookmarks_userprofile (
  user_id, theme, bookmark_date_display, bookmark_link_target,
  web_archive_integration, enable_sharing, enable_favicons, tag_search,
  display_url, permanent_notes, enable_public_sharing, search_preferences,
  custom_css, bookmark_description_display, bookmark_description_max_lines,
  display_archive_bookmark_action, display_edit_bookmark_action,
  display_remove_bookmark_action, display_view_bookmark_action,
  enable_automatic_html_snapshots, default_mark_unread, enable_preview_images,
  tag_grouping, auto_tagging_rules, items_per_page, sticky_pagination,
  custom_css_hash, collapse_side_panel, hide_bundles, default_mark_shared,
  legacy_search)
VALUES (
  $1, 'auto', 'relative', '_blank',
  'disabled', false, false, 'strict',
  false, false, false, '{}'::jsonb,
  '', 'inline', 1,
  true, true,
  true, true,
  true, false, false,
  'alphabetical', '', 30, false,
  '', false, false, false,
  false)
ON CONFLICT (user_id) DO NOTHING
''',
          [userId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> updateProfile(
    int userId,
    String theme,
    String bookmarkDateDisplay,
    String bookmarkDescriptionDisplay,
    int bookmarkDescriptionMaxLines,
    String bookmarkLinkTarget,
    String webArchiveIntegration,
    String tagSearch,
    String tagGrouping,
    bool enableSharing,
    bool enablePublicSharing,
    bool enableFavicons,
    bool enablePreviewImages,
    bool displayUrl,
    bool displayViewBookmarkAction,
    bool displayEditBookmarkAction,
    bool displayArchiveBookmarkAction,
    bool displayRemoveBookmarkAction,
    bool permanentNotes,
    String customCss,
    String customCssHash,
    String autoTaggingRules,
    bool enableAutomaticHtmlSnapshots,
    bool defaultMarkUnread,
    bool defaultMarkShared,
    int itemsPerPage,
    bool stickyPagination,
    bool collapseSidePanel,
    bool hideBundles,
    bool legacySearch,
  ) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_userprofile SET
  theme = $2, bookmark_date_display = $3, bookmark_description_display = $4,
  bookmark_description_max_lines = $5, bookmark_link_target = $6,
  web_archive_integration = $7, tag_search = $8, tag_grouping = $9,
  enable_sharing = $10, enable_public_sharing = $11, enable_favicons = $12,
  enable_preview_images = $13, display_url = $14,
  display_view_bookmark_action = $15, display_edit_bookmark_action = $16,
  display_archive_bookmark_action = $17, display_remove_bookmark_action = $18,
  permanent_notes = $19, custom_css = $20, custom_css_hash = $21,
  auto_tagging_rules = $22, enable_automatic_html_snapshots = $23,
  default_mark_unread = $24, default_mark_shared = $25, items_per_page = $26,
  sticky_pagination = $27, collapse_side_panel = $28, hide_bundles = $29,
  legacy_search = $30
WHERE user_id = $1
''',
          [
            userId,
            theme,
            bookmarkDateDisplay,
            bookmarkDescriptionDisplay,
            bookmarkDescriptionMaxLines,
            bookmarkLinkTarget,
            webArchiveIntegration,
            tagSearch,
            tagGrouping,
            enableSharing,
            enablePublicSharing,
            enableFavicons,
            enablePreviewImages,
            displayUrl,
            displayViewBookmarkAction,
            displayEditBookmarkAction,
            displayArchiveBookmarkAction,
            displayRemoveBookmarkAction,
            permanentNotes,
            customCss,
            customCssHash,
            autoTaggingRules,
            enableAutomaticHtmlSnapshots,
            defaultMarkUnread,
            defaultMarkShared,
            itemsPerPage,
            stickyPagination,
            collapseSidePanel,
            hideBundles,
            legacySearch,
          ],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> setSearchPreferences(
    int userId,
    String json,
  ) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_userprofile SET search_preferences = $2::jsonb
WHERE user_id = $1
''',
          [userId, json],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> setCollapseSidePanel(int userId, bool value) {
    return _db
        .execute(
          r'''
UPDATE bookmarks_userprofile SET collapse_side_panel = $2 WHERE user_id = $1
''',
          [userId, value],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<ApiTokenRow, SqlxError>> insertApiToken(
    String key,
    String name,
    DateTime created,
    int userId,
  ) {
    return _db.fetchOne<ApiTokenRow>(
      r'''
INSERT INTO bookmarks_apitoken (key, name, created, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, key, name, created, user_id
''',
      [key, name, created, userId],
      const $ApiTokenRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<ApiTokenRow>, SqlxError>> apiTokens(int userId) {
    return _db.fetchAll<ApiTokenRow>(
      r'''
SELECT id, key, name, created, user_id FROM bookmarks_apitoken
WHERE user_id = $1 ORDER BY created DESC, id DESC
''',
      [userId],
      const $ApiTokenRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteApiToken(int id, int userId) {
    return _db
        .execute(
          r'''DELETE FROM bookmarks_apitoken WHERE id = $1 AND user_id = $2''',
          [id, userId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<String?, SqlxError>> feedToken(int userId) {
    return _db.fetchScalar<String?>(
      r'''SELECT key FROM bookmarks_feedtoken WHERE user_id = $1''',
      [userId],
    );
  }

  @override
  Future<Result<Unit, SqlxError>> insertFeedToken(
    String key,
    DateTime created,
    int userId,
  ) {
    return _db
        .execute(
          r'''
INSERT INTO bookmarks_feedtoken (key, created, user_id) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
''',
          [key, created, userId],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byFeedToken(String key) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM bookmarks_feedtoken f JOIN auth_user u ON u.id = f.user_id
WHERE f.key = $1
''',
      [key],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> insertSession(
    String key,
    int userId,
    DateTime expires,
  ) {
    return _db
        .execute(
          r'''
INSERT INTO clone_session (session_key, user_id, expire_date)
VALUES ($1, $2, $3)
''',
          [key, userId, expires],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteSession(String key) {
    return _db
        .execute(r'''DELETE FROM clone_session WHERE session_key = $1''', [key])
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> renewSession(
    String key,
    String newKey,
    DateTime expires,
  ) {
    return _db
        .execute(
          r'''
UPDATE clone_session SET session_key = $2, expire_date = $3
WHERE session_key = $1
''',
          [key, newKey, expires],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteOtherSessions(int userId, String keep) {
    return _db
        .execute(
          r'''DELETE FROM clone_session WHERE user_id = $1 AND session_key <> $2''',
          [userId, keep],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteExpiredSessions(DateTime now) {
    return _db
        .execute(
          r'''DELETE FROM clone_session WHERE expire_date <= $1''',
          [now],
        )
        .then(
          (result) =>
              result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
        );
  }
}
