// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmark_list_repo.dart';

final class _$BookmarkListRepo implements BookmarkListRepo {
  const _$BookmarkListRepo(this._db);

  final Executor _db;

  @override
  Future<Result<List<BookmarkRow>, SqlxError>> list(int? ownerId, String list, bool publicOnly, DateTime? modifiedSince, DateTime? addedSince, String unread, String shared, String sort) {
    return _db.fetchAll<BookmarkRow>(
      r'''
SELECT b.id, b.url, b.url_normalized, b.title, b.description, b.notes,
       b.web_archive_snapshot_url, b.favicon_file, b.preview_image_file,
       b.unread, b.is_archived, b.shared, b.date_added, b.date_modified,
       b.date_accessed, b.owner_id, b.latest_snapshot_id
FROM bookmarks_bookmark b
WHERE ($1::integer IS NULL OR b.owner_id = $1)
  AND CASE $2::text
        WHEN 'active' THEN NOT b.is_archived
        WHEN 'archived' THEN b.is_archived
        ELSE b.shared AND EXISTS (
          SELECT 1 FROM bookmarks_userprofile p
          WHERE p.user_id = b.owner_id AND p.enable_sharing
            AND (NOT $3::boolean OR p.enable_public_sharing))
      END
  AND ($4::timestamptz IS NULL OR b.date_modified > $4)
  AND ($5::timestamptz IS NULL OR b.date_added > $5)
  AND ($6::text NOT IN ('yes', 'no') OR b.unread = ($6 = 'yes'))
  AND ($7::text NOT IN ('yes', 'no') OR b.shared = ($7 = 'yes'))
ORDER BY
  CASE WHEN $8::text = 'title_asc' THEN
    CASE WHEN b.title <> '' THEN lower(b.title) ELSE lower(b.url) END END ASC,
  CASE WHEN $8 = 'title_desc' THEN
    CASE WHEN b.title <> '' THEN lower(b.title) ELSE lower(b.url) END END DESC,
  CASE WHEN $8 = 'added_asc' THEN b.date_added END ASC,
  CASE WHEN $8 = 'modified_asc' THEN b.date_modified END ASC,
  CASE WHEN $8 = 'modified_desc' THEN b.date_modified END DESC,
  CASE WHEN $8 NOT IN ('title_asc', 'title_desc', 'added_asc',
                       'modified_asc', 'modified_desc')
       THEN b.date_added END DESC,
  CASE WHEN $8 IN ('title_asc', 'added_asc', 'modified_asc') THEN b.id END ASC,
  b.id DESC
''',
      [ownerId, list, publicOnly, modifiedSince, addedSince, unread, shared, sort],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<BookmarkRow>, SqlxError>> allOwned(int ownerId) {
    return _db.fetchAll<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE owner_id = $1
''',
      [ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<BookmarkRow>, SqlxError>> withNormalizedUrls(int ownerId, List<String> normalizedUrls) {
    return _db.fetchAll<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE owner_id = $1 AND url_normalized = ANY($2)
''',
      [ownerId, normalizedUrls],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> importUpdate(int id, String url, String urlNormalized, DateTime dateAdded, DateTime dateModified, bool unread, bool shared, String title, String description, String notes) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET
  url = $2, url_normalized = $3, date_added = $4, date_modified = $5,
  unread = $6, shared = $7, title = $8, description = $9, notes = $10
WHERE id = $1
''',
      [id, url, urlNormalized, dateAdded, dateModified, unread, shared, title, description, notes],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
