// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmark_states_repo.dart';

final class _$BookmarkStatesRepo implements BookmarkStatesRepo {
  const _$BookmarkStatesRepo(this._db);

  final Executor _db;

  @override
  Future<Result<Unit, SqlxError>> setArchived(int ownerId, List<int> ids, bool archived, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET is_archived = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, archived, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setUnread(int ownerId, List<int> ids, bool unread, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET unread = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, unread, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setShared(int ownerId, List<int> ids, bool shared, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET shared = $3, date_modified = $4
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, shared, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setState(int id, int ownerId, bool isArchived, bool unread, bool shared) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET is_archived = $3, unread = $4, shared = $5
WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId, isArchived, unread, shared],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> markRead(int id, int ownerId) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET unread = false WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> touch(int ownerId, List<int> ids, DateTime now) {
    return _db.execute(
      r'''
UPDATE bookmarks_bookmark SET date_modified = $3
WHERE owner_id = $1 AND id = ANY($2)
''',
      [ownerId, ids, now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<List<IdRow>, SqlxError>> ownedIds(int ownerId, List<int> ids) {
    return _db.fetchAll<IdRow>(
      r'''
SELECT id FROM bookmarks_bookmark WHERE owner_id = $1 AND id = ANY($2)
ORDER BY id
''',
      [ownerId, ids],
      const $IdRowRowDeserializer().deserialize,
    );
  }
}
