// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmark_tags_repo.dart';

final class _$BookmarkTagsRepo implements BookmarkTagsRepo {
  const _$BookmarkTagsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<List<BookmarkTagRow>, SqlxError>> tagNames(List<int> bookmarkIds) {
    return _db.fetchAll<BookmarkTagRow>(
      r'''
SELECT bt.bookmark_id, t.id AS tag_id, t.name
FROM bookmarks_bookmark_tags bt JOIN bookmarks_tag t ON t.id = bt.tag_id
WHERE bt.bookmark_id = ANY($1)
ORDER BY t.id
''',
      [bookmarkIds],
      const $BookmarkTagRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unlinkOtherTags(int bookmarkId, List<int> tagIds) {
    return _db.execute(
      r'''
DELETE FROM bookmarks_bookmark_tags
WHERE bookmark_id = $1 AND NOT (tag_id = ANY($2))
''',
      [bookmarkId, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> linkTags(int bookmarkId, List<int> tagIds) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_bookmark_tags (bookmark_id, tag_id)
SELECT $1, tag_id FROM unnest($2::integer[]) AS tag_id
ON CONFLICT (bookmark_id, tag_id) DO NOTHING
''',
      [bookmarkId, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> linkAll(List<int> bookmarkIds, List<int> tagIds) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_bookmark_tags (bookmark_id, tag_id)
SELECT b, t FROM unnest($1::integer[]) AS b, unnest($2::integer[]) AS t
ON CONFLICT (bookmark_id, tag_id) DO NOTHING
''',
      [bookmarkIds, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> unlinkAll(List<int> bookmarkIds, List<int> tagIds) {
    return _db.execute(
      r'''
DELETE FROM bookmarks_bookmark_tags
WHERE bookmark_id = ANY($1) AND tag_id = ANY($2)
''',
      [bookmarkIds, tagIds],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
