// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmarks_repo.dart';

final class _$BookmarksRepo implements BookmarksRepo {
  const _$BookmarksRepo(this._db);

  final Executor _db;

  @override
  Future<Result<BookmarkRow?, SqlxError>> owned(int id, int ownerId) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE id = $1 AND owner_id = $2
''',
      [id, ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark WHERE id = $1
''',
      [id],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow?, SqlxError>> existing(int ownerId, String normalizedUrl, String url) {
    return _db.fetchOptional<BookmarkRow>(
      r'''
SELECT id, url, url_normalized, title, description, notes,
       web_archive_snapshot_url, favicon_file, preview_image_file, unread,
       is_archived, shared, date_added, date_modified, date_accessed, owner_id,
       latest_snapshot_id
FROM bookmarks_bookmark
WHERE owner_id = $1
  AND (url_normalized = $2 OR (url_normalized = '' AND url = $3))
ORDER BY id
LIMIT 1
''',
      [ownerId, normalizedUrl, url],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<bool, SqlxError>> urlTaken(int ownerId, String url, int id) {
    return _db.fetchScalar<bool>(
      r'''
SELECT EXISTS (
  SELECT 1 FROM bookmarks_bookmark
  WHERE owner_id = $1 AND url = $2 AND id <> $3
) AS taken
''',
      [ownerId, url, id],
    );
  }

  @override
  Future<Result<bool, SqlxError>> duplicate(int ownerId, String normalizedUrl, String url, int id) {
    return _db.fetchScalar<bool>(
      r'''
SELECT EXISTS (
  SELECT 1 FROM bookmarks_bookmark
  WHERE owner_id = $1
    AND (url_normalized = $2 OR (url_normalized = '' AND url = $3))
    AND id <> $4
) AS duplicate
''',
      [ownerId, normalizedUrl, url, id],
    );
  }

  @override
  Future<Result<BookmarkRow, SqlxError>> insert(String url, String urlNormalized, String title, String description, String notes, bool unread, bool isArchived, bool shared, DateTime dateAdded, DateTime dateModified, int ownerId) {
    return _db.fetchOne<BookmarkRow>(
      r'''
INSERT INTO bookmarks_bookmark (
  url, url_normalized, title, description, notes, website_title,
  website_description, web_archive_snapshot_url, favicon_file,
  preview_image_file, unread, is_archived, shared, date_added, date_modified,
  date_accessed, owner_id, latest_snapshot_id)
VALUES ($1, $2, $3, $4, $5, NULL, NULL, '', '', '', $6, $7, $8, $9, $10, NULL,
        $11, NULL)
RETURNING id, url, url_normalized, title, description, notes,
          web_archive_snapshot_url, favicon_file, preview_image_file, unread,
          is_archived, shared, date_added, date_modified, date_accessed,
          owner_id, latest_snapshot_id
''',
      [url, urlNormalized, title, description, notes, unread, isArchived, shared, dateAdded, dateModified, ownerId],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<BookmarkRow, SqlxError>> update(int id, String url, String urlNormalized, String title, String description, String notes, bool unread, bool isArchived, bool shared, DateTime dateAdded, DateTime dateModified) {
    return _db.fetchOne<BookmarkRow>(
      r'''
UPDATE bookmarks_bookmark SET
  url = $2, url_normalized = $3, title = $4, description = $5, notes = $6,
  unread = $7, is_archived = $8, shared = $9, date_added = $10,
  date_modified = $11
WHERE id = $1
RETURNING id, url, url_normalized, title, description, notes,
          web_archive_snapshot_url, favicon_file, preview_image_file, unread,
          is_archived, shared, date_added, date_modified, date_accessed,
          owner_id, latest_snapshot_id
''',
      [id, url, urlNormalized, title, description, notes, unread, isArchived, shared, dateAdded, dateModified],
      const $BookmarkRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<FileRow>, SqlxError>> delete(int id, int ownerId) {
    return _db.fetchAll<FileRow>(
      r'''
WITH gone AS (
  DELETE FROM bookmarks_bookmark WHERE id = $1 AND owner_id = $2 RETURNING id
), links AS (
  DELETE FROM bookmarks_bookmark_tags WHERE bookmark_id IN (SELECT id FROM gone)
)
DELETE FROM bookmarks_bookmarkasset
WHERE bookmark_id IN (SELECT id FROM gone)
RETURNING file
''',
      [id, ownerId],
      const $FileRowRowDeserializer().deserialize,
    );
  }
}
