// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'profiles_repo.dart';

final class _$ProfilesRepo implements ProfilesRepo {
  const _$ProfilesRepo(this._db);

  final Executor _db;

  @override
  Future<Result<ProfileRow?, SqlxError>> profile(int userId) {
    return _db.fetchOptional<ProfileRow>(
      r'''
SELECT id, user_id, theme, bookmark_date_display, bookmark_description_display,
       bookmark_description_max_lines, bookmark_link_target,
       web_archive_integration, tag_search, tag_grouping, enable_sharing,
       enable_public_sharing, enable_favicons, enable_preview_images,
       display_url, display_view_bookmark_action, display_edit_bookmark_action,
       display_archive_bookmark_action, display_remove_bookmark_action,
       permanent_notes, custom_css, custom_css_hash, auto_tagging_rules,
       search_preferences::text AS search_preferences_json,
       enable_automatic_html_snapshots, default_mark_unread,
       default_mark_shared, items_per_page, sticky_pagination,
       collapse_side_panel, hide_bundles, legacy_search
FROM bookmarks_userprofile WHERE user_id = $1
''',
      [userId],
      const $ProfileRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> insertDefaultProfile(int userId) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_userprofile (
  user_id, theme, bookmark_date_display, bookmark_link_target,
  web_archive_integration, enable_sharing, enable_favicons, tag_search,
  display_url, permanent_notes, enable_public_sharing, search_preferences,
  custom_css, bookmark_description_display, bookmark_description_max_lines,
  display_archive_bookmark_action, display_edit_bookmark_action,
  display_remove_bookmark_action, display_view_bookmark_action,
  enable_automatic_html_snapshots, default_mark_unread, enable_preview_images,
  tag_grouping, auto_tagging_rules, items_per_page, sticky_pagination,
  custom_css_hash, collapse_side_panel, hide_bundles, default_mark_shared,
  legacy_search)
VALUES (
  $1, 'auto', 'relative', '_blank',
  'disabled', false, false, 'strict',
  false, false, false, '{}'::jsonb,
  '', 'inline', 1,
  true, true,
  true, true,
  true, false, false,
  'alphabetical', '', 30, false,
  '', false, false, false,
  false)
ON CONFLICT (user_id) DO NOTHING
''',
      [userId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> updateProfile(int userId, String theme, String bookmarkDateDisplay, String bookmarkDescriptionDisplay, int bookmarkDescriptionMaxLines, String bookmarkLinkTarget, String webArchiveIntegration, String tagSearch, String tagGrouping, bool enableSharing, bool enablePublicSharing, bool enableFavicons, bool enablePreviewImages, bool displayUrl, bool displayViewBookmarkAction, bool displayEditBookmarkAction, bool displayArchiveBookmarkAction, bool displayRemoveBookmarkAction, bool permanentNotes, String customCss, String customCssHash, String autoTaggingRules, bool enableAutomaticHtmlSnapshots, bool defaultMarkUnread, bool defaultMarkShared, int itemsPerPage, bool stickyPagination, bool collapseSidePanel, bool hideBundles, bool legacySearch) {
    return _db.execute(
      r'''
UPDATE bookmarks_userprofile SET
  theme = $2, bookmark_date_display = $3, bookmark_description_display = $4,
  bookmark_description_max_lines = $5, bookmark_link_target = $6,
  web_archive_integration = $7, tag_search = $8, tag_grouping = $9,
  enable_sharing = $10, enable_public_sharing = $11, enable_favicons = $12,
  enable_preview_images = $13, display_url = $14,
  display_view_bookmark_action = $15, display_edit_bookmark_action = $16,
  display_archive_bookmark_action = $17, display_remove_bookmark_action = $18,
  permanent_notes = $19, custom_css = $20, custom_css_hash = $21,
  auto_tagging_rules = $22, enable_automatic_html_snapshots = $23,
  default_mark_unread = $24, default_mark_shared = $25, items_per_page = $26,
  sticky_pagination = $27, collapse_side_panel = $28, hide_bundles = $29,
  legacy_search = $30
WHERE user_id = $1
''',
      [userId, theme, bookmarkDateDisplay, bookmarkDescriptionDisplay, bookmarkDescriptionMaxLines, bookmarkLinkTarget, webArchiveIntegration, tagSearch, tagGrouping, enableSharing, enablePublicSharing, enableFavicons, enablePreviewImages, displayUrl, displayViewBookmarkAction, displayEditBookmarkAction, displayArchiveBookmarkAction, displayRemoveBookmarkAction, permanentNotes, customCss, customCssHash, autoTaggingRules, enableAutomaticHtmlSnapshots, defaultMarkUnread, defaultMarkShared, itemsPerPage, stickyPagination, collapseSidePanel, hideBundles, legacySearch],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setSearchPreferences(int userId, String json) {
    return _db.execute(
      r'''
UPDATE bookmarks_userprofile SET search_preferences = $2::jsonb
WHERE user_id = $1
''',
      [userId, json],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setCollapseSidePanel(int userId, bool value) {
    return _db.execute(
      r'''
UPDATE bookmarks_userprofile SET collapse_side_panel = $2 WHERE user_id = $1
''',
      [userId, value],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
