// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'sessions_repo.dart';

final class _$SessionsRepo implements SessionsRepo {
  const _$SessionsRepo(this._db);

  final Executor _db;

  @override
  Future<Result<Unit, SqlxError>> insertSession(String key, int userId, DateTime expires) {
    return _db.execute(
      r'''
INSERT INTO clone_session (session_key, user_id, expire_date)
VALUES ($1, $2, $3)
''',
      [key, userId, expires],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteSession(String key) {
    return _db.execute(
      r'''DELETE FROM clone_session WHERE session_key = $1''',
      [key],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> renewSession(String key, String newKey, DateTime expires) {
    return _db.execute(
      r'''
UPDATE clone_session SET session_key = $2, expire_date = $3
WHERE session_key = $1
''',
      [key, newKey, expires],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteOtherSessions(int userId, String keep) {
    return _db.execute(
      r'''DELETE FROM clone_session WHERE user_id = $1 AND session_key <> $2''',
      [userId, keep],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteExpiredSessions(DateTime now) {
    return _db.execute(
      r'''DELETE FROM clone_session WHERE expire_date <= $1''',
      [now],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
