// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tokens_repo.dart';

final class _$TokensRepo implements TokensRepo {
  const _$TokensRepo(this._db);

  final Executor _db;

  @override
  Future<Result<ApiTokenRow, SqlxError>> insertApiToken(String key, String name, DateTime created, int userId) {
    return _db.fetchOne<ApiTokenRow>(
      r'''
INSERT INTO bookmarks_apitoken (key, name, created, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, key, name, created, user_id
''',
      [key, name, created, userId],
      const $ApiTokenRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<ApiTokenRow>, SqlxError>> apiTokens(int userId) {
    return _db.fetchAll<ApiTokenRow>(
      r'''
SELECT id, key, name, created, user_id FROM bookmarks_apitoken
WHERE user_id = $1 ORDER BY created DESC, id DESC
''',
      [userId],
      const $ApiTokenRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> deleteApiToken(int id, int userId) {
    return _db.execute(
      r'''DELETE FROM bookmarks_apitoken WHERE id = $1 AND user_id = $2''',
      [id, userId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<String?, SqlxError>> feedToken(int userId) {
    return _db.fetchScalar<String?>(
      r'''SELECT key FROM bookmarks_feedtoken WHERE user_id = $1''',
      [userId],
    );
  }

  @override
  Future<Result<Unit, SqlxError>> insertFeedToken(String key, DateTime created, int userId) {
    return _db.execute(
      r'''
INSERT INTO bookmarks_feedtoken (key, created, user_id) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
''',
      [key, created, userId],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }
}
