// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'users_repo.dart';

final class _$UsersRepo implements UsersRepo {
  const _$UsersRepo(this._db);

  final Executor _db;

  @override
  Future<Result<UserRow?, SqlxError>> byUsername(String username) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, password, last_login, is_superuser, username, first_name,
       last_name, email, is_staff, is_active, date_joined
FROM auth_user WHERE username = $1
''',
      [username],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byId(int id) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT id, password, last_login, is_superuser, username, first_name,
       last_name, email, is_staff, is_active, date_joined
FROM auth_user WHERE id = $1
''',
      [id],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byApiToken(String key) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM bookmarks_apitoken t JOIN auth_user u ON u.id = t.user_id
WHERE t.key = $1
''',
      [key],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> bySession(String key, DateTime now) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM clone_session s JOIN auth_user u ON u.id = s.user_id
WHERE s.session_key = $1 AND s.expire_date > $2
''',
      [key, now],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow?, SqlxError>> byFeedToken(String key) {
    return _db.fetchOptional<UserRow>(
      r'''
SELECT u.id, u.password, u.last_login, u.is_superuser, u.username,
       u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
       u.date_joined
FROM bookmarks_feedtoken f JOIN auth_user u ON u.id = f.user_id
WHERE f.key = $1
''',
      [key],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<UserRow, SqlxError>> insert(String password, bool isSuperuser, String username, String email, DateTime dateJoined) {
    return _db.fetchOne<UserRow>(
      r'''
INSERT INTO auth_user (password, last_login, is_superuser, username,
                       first_name, last_name, email, is_staff, is_active,
                       date_joined)
VALUES ($1, NULL, $2, $3, '', '', $4, $2, true, $5)
RETURNING id, password, last_login, is_superuser, username, first_name,
          last_name, email, is_staff, is_active, date_joined
''',
      [password, isSuperuser, username, email, dateJoined],
      const $UserRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setPassword(int id, String password) {
    return _db.execute(
      r'''UPDATE auth_user SET password = $2 WHERE id = $1''',
      [id, password],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<Unit, SqlxError>> setLastLogin(int id, DateTime at) {
    return _db.execute(
      r'''UPDATE auth_user SET last_login = $2 WHERE id = $1''',
      [id, at],
    ).then(
      (result) => result.andThen<Unit>((_) => const Ok<Unit, SqlxError>(unit)),
    );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> activeUsers() {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user WHERE is_active ORDER BY username''',
      [],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> allUsers() {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user''',
      [],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<UserNameRow>, SqlxError>> names(List<int> ids) {
    return _db.fetchAll<UserNameRow>(
      r'''SELECT id, username FROM auth_user WHERE id = ANY($1) ORDER BY id''',
      [ids],
      const $UserNameRowRowDeserializer().deserialize,
    );
  }
}
