// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bookmark_rows.dart';

BookmarkRow _$BookmarkRowFromRow(Row row) {
  return BookmarkRow(
    id: row.read<int>('id'),
    url: row.read<String>('url'),
    urlNormalized: row.read<String>('url_normalized'),
    title: row.read<String>('title'),
    description: row.read<String>('description'),
    notes: row.read<String>('notes'),
    webArchiveSnapshotUrl: row.read<String>('web_archive_snapshot_url'),
    faviconFile: row.read<String>('favicon_file'),
    previewImageFile: row.read<String>('preview_image_file'),
    unread: row.readBool('unread'),
    isArchived: row.readBool('is_archived'),
    shared: row.readBool('shared'),
    dateAdded: row.readDateTime('date_added'),
    dateModified: row.readDateTime('date_modified'),
    ownerId: row.read<int>('owner_id'),
    dateAccessed: row.readDateTimeNullable('date_accessed'),
    latestSnapshotId: row.readNullable<int>('latest_snapshot_id'),
  );
}

/// Row deserializer for [BookmarkRow].
final class $BookmarkRowRowDeserializer implements RowDeserializer<BookmarkRow> {
  const $BookmarkRowRowDeserializer();

  @override
  BookmarkRow deserialize(Row row) => _$BookmarkRowFromRow(row);
}

/// Typed row query terminals for [BookmarkRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BookmarkRowQuery on QueryAs<BookmarkRow> {
  /// Fetches exactly one row.
  Future<Result<BookmarkRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BookmarkRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BookmarkRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BookmarkRowFromRow);

  /// Fetches every row.
  Future<Result<List<BookmarkRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BookmarkRowFromRow);
}

BookmarkTagRow _$BookmarkTagRowFromRow(Row row) {
  return BookmarkTagRow(
    bookmarkId: row.read<int>('bookmark_id'),
    tagId: row.read<int>('tag_id'),
    name: row.read<String>('name'),
  );
}

/// Row deserializer for [BookmarkTagRow].
final class $BookmarkTagRowRowDeserializer implements RowDeserializer<BookmarkTagRow> {
  const $BookmarkTagRowRowDeserializer();

  @override
  BookmarkTagRow deserialize(Row row) => _$BookmarkTagRowFromRow(row);
}

/// Typed row query terminals for [BookmarkTagRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BookmarkTagRowQuery on QueryAs<BookmarkTagRow> {
  /// Fetches exactly one row.
  Future<Result<BookmarkTagRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BookmarkTagRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BookmarkTagRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BookmarkTagRowFromRow);

  /// Fetches every row.
  Future<Result<List<BookmarkTagRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BookmarkTagRowFromRow);
}

AssetRow _$AssetRowFromRow(Row row) {
  return AssetRow(
    id: row.read<int>('id'),
    dateCreated: row.readDateTime('date_created'),
    file: row.read<String>('file'),
    fileSize: row.readNullable<int>('file_size'),
    assetType: row.read<String>('asset_type'),
    contentType: row.read<String>('content_type'),
    displayName: row.read<String>('display_name'),
    status: row.read<String>('status'),
    gzip: row.readBool('gzip'),
    bookmarkId: row.read<int>('bookmark_id'),
  );
}

/// Row deserializer for [AssetRow].
final class $AssetRowRowDeserializer implements RowDeserializer<AssetRow> {
  const $AssetRowRowDeserializer();

  @override
  AssetRow deserialize(Row row) => _$AssetRowFromRow(row);
}

/// Typed row query terminals for [AssetRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AssetRowQuery on QueryAs<AssetRow> {
  /// Fetches exactly one row.
  Future<Result<AssetRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$AssetRowFromRow);

  /// Fetches zero or one row.
  Future<Result<AssetRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$AssetRowFromRow);

  /// Fetches every row.
  Future<Result<List<AssetRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$AssetRowFromRow);
}

IdRow _$IdRowFromRow(Row row) {
  return IdRow(id: row.read<int>('id'));
}

/// Row deserializer for [IdRow].
final class $IdRowRowDeserializer implements RowDeserializer<IdRow> {
  const $IdRowRowDeserializer();

  @override
  IdRow deserialize(Row row) => _$IdRowFromRow(row);
}

/// Typed row query terminals for [IdRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $IdRowQuery on QueryAs<IdRow> {
  /// Fetches exactly one row.
  Future<Result<IdRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$IdRowFromRow);

  /// Fetches zero or one row.
  Future<Result<IdRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$IdRowFromRow);

  /// Fetches every row.
  Future<Result<List<IdRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$IdRowFromRow);
}

FileRow _$FileRowFromRow(Row row) {
  return FileRow(file: row.read<String>('file'));
}

/// Row deserializer for [FileRow].
final class $FileRowRowDeserializer implements RowDeserializer<FileRow> {
  const $FileRowRowDeserializer();

  @override
  FileRow deserialize(Row row) => _$FileRowFromRow(row);
}

/// Typed row query terminals for [FileRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $FileRowQuery on QueryAs<FileRow> {
  /// Fetches exactly one row.
  Future<Result<FileRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$FileRowFromRow);

  /// Fetches zero or one row.
  Future<Result<FileRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$FileRowFromRow);

  /// Fetches every row.
  Future<Result<List<FileRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$FileRowFromRow);
}
