// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'bundle_row.dart';

BundleRow _$BundleRowFromRow(Row row) {
  return BundleRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    search: row.read<String>('search'),
    anyTags: row.read<String>('any_tags'),
    allTags: row.read<String>('all_tags'),
    excludedTags: row.read<String>('excluded_tags'),
    filterUnread: row.read<String>('filter_unread'),
    filterShared: row.read<String>('filter_shared'),
    order: row.read<int>('order'),
    dateCreated: row.readDateTime('date_created'),
    dateModified: row.readDateTime('date_modified'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [BundleRow].
final class $BundleRowRowDeserializer implements RowDeserializer<BundleRow> {
  const $BundleRowRowDeserializer();

  @override
  BundleRow deserialize(Row row) => _$BundleRowFromRow(row);
}

/// Typed row query terminals for [BundleRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $BundleRowQuery on QueryAs<BundleRow> {
  /// Fetches exactly one row.
  Future<Result<BundleRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$BundleRowFromRow);

  /// Fetches zero or one row.
  Future<Result<BundleRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$BundleRowFromRow);

  /// Fetches every row.
  Future<Result<List<BundleRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$BundleRowFromRow);
}
