// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'profile_row.dart';

ProfileRow _$ProfileRowFromRow(Row row) {
  return ProfileRow(
    id: row.read<int>('id'),
    userId: row.read<int>('user_id'),
    theme: row.read<String>('theme'),
    bookmarkDateDisplay: row.read<String>('bookmark_date_display'),
    bookmarkDescriptionDisplay: row.read<String>('bookmark_description_display'),
    bookmarkDescriptionMaxLines: row.read<int>('bookmark_description_max_lines'),
    bookmarkLinkTarget: row.read<String>('bookmark_link_target'),
    webArchiveIntegration: row.read<String>('web_archive_integration'),
    tagSearch: row.read<String>('tag_search'),
    tagGrouping: row.read<String>('tag_grouping'),
    enableSharing: row.readBool('enable_sharing'),
    enablePublicSharing: row.readBool('enable_public_sharing'),
    enableFavicons: row.readBool('enable_favicons'),
    enablePreviewImages: row.readBool('enable_preview_images'),
    displayUrl: row.readBool('display_url'),
    displayViewBookmarkAction: row.readBool('display_view_bookmark_action'),
    displayEditBookmarkAction: row.readBool('display_edit_bookmark_action'),
    displayArchiveBookmarkAction: row.readBool('display_archive_bookmark_action'),
    displayRemoveBookmarkAction: row.readBool('display_remove_bookmark_action'),
    permanentNotes: row.readBool('permanent_notes'),
    customCss: row.read<String>('custom_css'),
    customCssHash: row.read<String>('custom_css_hash'),
    autoTaggingRules: row.read<String>('auto_tagging_rules'),
    searchPreferencesJson: row.read<String>('search_preferences_json'),
    enableAutomaticHtmlSnapshots: row.readBool('enable_automatic_html_snapshots'),
    defaultMarkUnread: row.readBool('default_mark_unread'),
    defaultMarkShared: row.readBool('default_mark_shared'),
    itemsPerPage: row.read<int>('items_per_page'),
    stickyPagination: row.readBool('sticky_pagination'),
    collapseSidePanel: row.readBool('collapse_side_panel'),
    hideBundles: row.readBool('hide_bundles'),
    legacySearch: row.readBool('legacy_search'),
  );
}

/// Row deserializer for [ProfileRow].
final class $ProfileRowRowDeserializer implements RowDeserializer<ProfileRow> {
  const $ProfileRowRowDeserializer();

  @override
  ProfileRow deserialize(Row row) => _$ProfileRowFromRow(row);
}

/// Typed row query terminals for [ProfileRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ProfileRowQuery on QueryAs<ProfileRow> {
  /// Fetches exactly one row.
  Future<Result<ProfileRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ProfileRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ProfileRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ProfileRowFromRow);

  /// Fetches every row.
  Future<Result<List<ProfileRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ProfileRowFromRow);
}
