// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'settings_rows.dart';

GlobalSettingsRow _$GlobalSettingsRowFromRow(Row row) {
  return GlobalSettingsRow(
    id: row.read<int>('id'),
    landingPage: row.read<String>('landing_page'),
    enableLinkPrefetch: row.readBool('enable_link_prefetch'),
    guestProfileUserId: row.readNullable<int>('guest_profile_user_id'),
  );
}

/// Row deserializer for [GlobalSettingsRow].
final class $GlobalSettingsRowRowDeserializer implements RowDeserializer<GlobalSettingsRow> {
  const $GlobalSettingsRowRowDeserializer();

  @override
  GlobalSettingsRow deserialize(Row row) => _$GlobalSettingsRowFromRow(row);
}

/// Typed row query terminals for [GlobalSettingsRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $GlobalSettingsRowQuery on QueryAs<GlobalSettingsRow> {
  /// Fetches exactly one row.
  Future<Result<GlobalSettingsRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$GlobalSettingsRowFromRow);

  /// Fetches zero or one row.
  Future<Result<GlobalSettingsRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$GlobalSettingsRowFromRow);

  /// Fetches every row.
  Future<Result<List<GlobalSettingsRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$GlobalSettingsRowFromRow);
}

ToastRow _$ToastRowFromRow(Row row) {
  return ToastRow(
    id: row.read<int>('id'),
    key: row.read<String>('key'),
    message: row.read<String>('message'),
    acknowledged: row.readBool('acknowledged'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [ToastRow].
final class $ToastRowRowDeserializer implements RowDeserializer<ToastRow> {
  const $ToastRowRowDeserializer();

  @override
  ToastRow deserialize(Row row) => _$ToastRowFromRow(row);
}

/// Typed row query terminals for [ToastRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ToastRowQuery on QueryAs<ToastRow> {
  /// Fetches exactly one row.
  Future<Result<ToastRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ToastRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ToastRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ToastRowFromRow);

  /// Fetches every row.
  Future<Result<List<ToastRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ToastRowFromRow);
}

MessageRow _$MessageRowFromRow(Row row) {
  return MessageRow(
    level: row.read<String>('level'),
    message: row.read<String>('message'),
    extraTags: row.read<String>('extra_tags'),
  );
}

/// Row deserializer for [MessageRow].
final class $MessageRowRowDeserializer implements RowDeserializer<MessageRow> {
  const $MessageRowRowDeserializer();

  @override
  MessageRow deserialize(Row row) => _$MessageRowFromRow(row);
}

/// Typed row query terminals for [MessageRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $MessageRowQuery on QueryAs<MessageRow> {
  /// Fetches exactly one row.
  Future<Result<MessageRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$MessageRowFromRow);

  /// Fetches zero or one row.
  Future<Result<MessageRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$MessageRowFromRow);

  /// Fetches every row.
  Future<Result<List<MessageRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$MessageRowFromRow);
}
