// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'tag_rows.dart';

TagRow _$TagRowFromRow(Row row) {
  return TagRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    dateAdded: row.readDateTime('date_added'),
    ownerId: row.read<int>('owner_id'),
  );
}

/// Row deserializer for [TagRow].
final class $TagRowRowDeserializer implements RowDeserializer<TagRow> {
  const $TagRowRowDeserializer();

  @override
  TagRow deserialize(Row row) => _$TagRowFromRow(row);
}

/// Typed row query terminals for [TagRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $TagRowQuery on QueryAs<TagRow> {
  /// Fetches exactly one row.
  Future<Result<TagRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$TagRowFromRow);

  /// Fetches zero or one row.
  Future<Result<TagRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$TagRowFromRow);

  /// Fetches every row.
  Future<Result<List<TagRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$TagRowFromRow);
}

TagUsageRow _$TagUsageRowFromRow(Row row) {
  return TagUsageRow(
    id: row.read<int>('id'),
    name: row.read<String>('name'),
    dateAdded: row.readDateTime('date_added'),
    bookmarkCount: row.read<int>('bookmark_count'),
  );
}

/// Row deserializer for [TagUsageRow].
final class $TagUsageRowRowDeserializer implements RowDeserializer<TagUsageRow> {
  const $TagUsageRowRowDeserializer();

  @override
  TagUsageRow deserialize(Row row) => _$TagUsageRowFromRow(row);
}

/// Typed row query terminals for [TagUsageRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $TagUsageRowQuery on QueryAs<TagUsageRow> {
  /// Fetches exactly one row.
  Future<Result<TagUsageRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$TagUsageRowFromRow);

  /// Fetches zero or one row.
  Future<Result<TagUsageRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$TagUsageRowFromRow);

  /// Fetches every row.
  Future<Result<List<TagUsageRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$TagUsageRowFromRow);
}
