// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'user_rows.dart';

UserRow _$UserRowFromRow(Row row) {
  return UserRow(
    id: row.read<int>('id'),
    password: row.read<String>('password'),
    isSuperuser: row.readBool('is_superuser'),
    username: row.read<String>('username'),
    firstName: row.read<String>('first_name'),
    lastName: row.read<String>('last_name'),
    email: row.read<String>('email'),
    isStaff: row.readBool('is_staff'),
    isActive: row.readBool('is_active'),
    dateJoined: row.readDateTime('date_joined'),
    lastLogin: row.readDateTimeNullable('last_login'),
  );
}

/// Row deserializer for [UserRow].
final class $UserRowRowDeserializer implements RowDeserializer<UserRow> {
  const $UserRowRowDeserializer();

  @override
  UserRow deserialize(Row row) => _$UserRowFromRow(row);
}

/// Typed row query terminals for [UserRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $UserRowQuery on QueryAs<UserRow> {
  /// Fetches exactly one row.
  Future<Result<UserRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$UserRowFromRow);

  /// Fetches zero or one row.
  Future<Result<UserRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$UserRowFromRow);

  /// Fetches every row.
  Future<Result<List<UserRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$UserRowFromRow);
}

UserNameRow _$UserNameRowFromRow(Row row) {
  return UserNameRow(
    id: row.read<int>('id'),
    username: row.read<String>('username'),
  );
}

/// Row deserializer for [UserNameRow].
final class $UserNameRowRowDeserializer implements RowDeserializer<UserNameRow> {
  const $UserNameRowRowDeserializer();

  @override
  UserNameRow deserialize(Row row) => _$UserNameRowFromRow(row);
}

/// Typed row query terminals for [UserNameRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $UserNameRowQuery on QueryAs<UserNameRow> {
  /// Fetches exactly one row.
  Future<Result<UserNameRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$UserNameRowFromRow);

  /// Fetches zero or one row.
  Future<Result<UserNameRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$UserNameRowFromRow);

  /// Fetches every row.
  Future<Result<List<UserNameRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$UserNameRowFromRow);
}

ApiTokenRow _$ApiTokenRowFromRow(Row row) {
  return ApiTokenRow(
    id: row.read<int>('id'),
    key: row.read<String>('key'),
    name: row.read<String>('name'),
    created: row.readDateTime('created'),
    userId: row.read<int>('user_id'),
  );
}

/// Row deserializer for [ApiTokenRow].
final class $ApiTokenRowRowDeserializer implements RowDeserializer<ApiTokenRow> {
  const $ApiTokenRowRowDeserializer();

  @override
  ApiTokenRow deserialize(Row row) => _$ApiTokenRowFromRow(row);
}

/// Typed row query terminals for [ApiTokenRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ApiTokenRowQuery on QueryAs<ApiTokenRow> {
  /// Fetches exactly one row.
  Future<Result<ApiTokenRow, SqlxError>> fetchOne(Executor db) =>
      fetchOneWith(db, _$ApiTokenRowFromRow);

  /// Fetches zero or one row.
  Future<Result<ApiTokenRow?, SqlxError>> fetchOptional(Executor db) =>
      fetchOptionalWith(db, _$ApiTokenRowFromRow);

  /// Fetches every row.
  Future<Result<List<ApiTokenRow>, SqlxError>> fetchAll(Executor db) =>
      fetchAllWith(db, _$ApiTokenRowFromRow);
}
