"""Writes the list of common passwords Django's `CommonPasswordValidator`
refuses, as the Dart source the server embeds: Django's gzipped list, in
base64.

    cd <linkding checkout> && uv run python <this file> \
        > packages/linkding_server/lib/src/auth/common_passwords.dart
"""

import base64
import pathlib

import django.contrib.auth

path = pathlib.Path(django.contrib.auth.__file__).parent / "common-passwords.txt.gz"
data = base64.b64encode(path.read_bytes()).decode()
lines = [data[i : i + 76] for i in range(0, len(data), 76)]

print(f"""// Generated by tool/common_passwords.py from Django {django.get_version()}; do not edit.
//
// Django's list of 20,000 common passwords (BSD-3-Clause, Copyright (c)
// Django Software Foundation and individual contributors), created by
// Royce Williams: gzipped, lowercased and deduplicated, in base64.

/// The gzipped list, one password per line.
const commonPasswordsGzipBase64 = '''
{chr(10).join(lines)}
''';""")
