-- REST API tokens (several per user) and the one key per user that unlocks
-- the RSS feeds.
CREATE TABLE bookmarks_apitoken (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key character varying(40) NOT NULL,
    name character varying(128) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT bookmarks_apitoken_key_key UNIQUE (key),
    CONSTRAINT bookmarks_apitoken_user_id_2181e9f8_fk_auth_user_id
        FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_apitoken_key_af12d964_like ON bookmarks_apitoken USING btree (key varchar_pattern_ops);
CREATE INDEX bookmarks_apitoken_user_id_2181e9f8 ON bookmarks_apitoken USING btree (user_id);

CREATE TABLE bookmarks_feedtoken (
    key character varying(40) NOT NULL PRIMARY KEY,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT bookmarks_feedtoken_user_id_key UNIQUE (user_id),
    CONSTRAINT bookmarks_feedtoken_user_id_47eef1a9_fk_auth_user_id
        FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_feedtoken_key_8609bd53_like ON bookmarks_feedtoken USING btree (key varchar_pattern_ops);
