-- Saved searches, shown in the sidebar in `order`.
CREATE TABLE bookmarks_bookmarkbundle (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(256) NOT NULL,
    search character varying(256) NOT NULL,
    any_tags character varying(1024) NOT NULL,
    all_tags character varying(1024) NOT NULL,
    excluded_tags character varying(1024) NOT NULL,
    "order" integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    owner_id integer NOT NULL,
    filter_shared character varying(3) NOT NULL,
    filter_unread character varying(3) NOT NULL,
    CONSTRAINT bookmarks_bookmarkbundle_owner_id_53ecd5a5_fk_auth_user_id
        FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_bookmarkbundle_owner_id_53ecd5a5 ON bookmarks_bookmarkbundle USING btree (owner_id);
