-- Django's one-time messages ("Tag created"), shown on the next page that
-- lists them. Django keeps them in a signed cookie; the clone keeps them
-- with the session they belong to.
CREATE TABLE clone_message (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key character varying(40) NOT NULL
        REFERENCES clone_session(session_key) ON DELETE CASCADE,
    level character varying(16) NOT NULL,
    message text NOT NULL,
    extra_tags character varying(64) NOT NULL
);
CREATE INDEX clone_message_session_key ON clone_message USING btree (session_key);
