-- Instance-wide settings (a single row) and the one-off notices shown after
-- an import or an upgrade.
CREATE TABLE bookmarks_globalsettings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landing_page character varying(50) NOT NULL,
    guest_profile_user_id integer,
    enable_link_prefetch boolean NOT NULL,
    CONSTRAINT bookmarks_globalsett_guest_profile_user_i_6d5cf00e_fk_auth_user
        FOREIGN KEY (guest_profile_user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_globalsettings_guest_profile_user_id_6d5cf00e ON bookmarks_globalsettings USING btree (guest_profile_user_id);

CREATE TABLE bookmarks_toast (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key character varying(50) NOT NULL,
    message text NOT NULL,
    acknowledged boolean NOT NULL,
    owner_id integer NOT NULL,
    CONSTRAINT bookmarks_toast_owner_id_7fa00b79_fk_auth_user_id
        FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_toast_owner_id_7fa00b79 ON bookmarks_toast USING btree (owner_id);
