-- Names are unique per owner ignoring case, which the application enforces;
-- linkding has no index for it either.
CREATE TABLE bookmarks_tag (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(64) NOT NULL,
    date_added timestamp with time zone NOT NULL,
    owner_id integer NOT NULL,
    CONSTRAINT bookmarks_tag_owner_id_4c853e4b_fk_auth_user_id
        FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_tag_owner_id_4c853e4b ON bookmarks_tag USING btree (owner_id);
