-- Bookmarks, their tags, and their assets (snapshots and uploads). A bookmark
-- points at its latest snapshot and an asset at its bookmark, so the second
-- reference is added once both tables exist. As in Django, foreign keys do
-- not cascade: deletes remove dependent rows first.
CREATE TABLE bookmarks_bookmark (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url character varying(2048) NOT NULL,
    title character varying(512) NOT NULL,
    description text NOT NULL,
    website_title character varying(512),
    website_description text,
    unread boolean NOT NULL,
    date_added timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_accessed timestamp with time zone,
    owner_id integer NOT NULL,
    is_archived boolean NOT NULL,
    web_archive_snapshot_url character varying(2048) NOT NULL,
    shared boolean NOT NULL,
    favicon_file character varying(512) NOT NULL,
    notes text NOT NULL,
    preview_image_file character varying(512) NOT NULL,
    latest_snapshot_id integer,
    url_normalized character varying(2048) NOT NULL,
    CONSTRAINT bookmarks_bookmark_owner_id_051b24cc_fk_auth_user_id
        FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_bookmark_owner_id_051b24cc ON bookmarks_bookmark USING btree (owner_id);
CREATE INDEX bookmarks_bookmark_latest_snapshot_id_ed3c8c2b ON bookmarks_bookmark USING btree (latest_snapshot_id);
CREATE INDEX bookmarks_bookmark_url_normalized_8b3c53e4 ON bookmarks_bookmark USING btree (url_normalized);
CREATE INDEX bookmarks_bookmark_url_normalized_8b3c53e4_like ON bookmarks_bookmark USING btree (url_normalized varchar_pattern_ops);

CREATE TABLE bookmarks_bookmarkasset (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_created timestamp with time zone NOT NULL,
    file character varying(2048) NOT NULL,
    file_size integer,
    asset_type character varying(64) NOT NULL,
    content_type character varying(128) NOT NULL,
    display_name character varying(2048) NOT NULL,
    status character varying(64) NOT NULL,
    gzip boolean NOT NULL,
    bookmark_id integer NOT NULL,
    CONSTRAINT bookmarks_bookmarkas_bookmark_id_42136c86_fk_bookmarks
        FOREIGN KEY (bookmark_id) REFERENCES bookmarks_bookmark(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_bookmarkasset_bookmark_id_42136c86 ON bookmarks_bookmarkasset USING btree (bookmark_id);

ALTER TABLE bookmarks_bookmark
    ADD CONSTRAINT bookmarks_bookmark_latest_snapshot_id_ed3c8c2b_fk_bookmarks
    FOREIGN KEY (latest_snapshot_id) REFERENCES bookmarks_bookmarkasset(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE bookmarks_bookmark_tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookmark_id integer NOT NULL,
    tag_id integer NOT NULL,
    CONSTRAINT bookmarks_bookmark_tags_bookmark_id_tag_id_1a999b75_uniq UNIQUE (bookmark_id, tag_id),
    CONSTRAINT bookmarks_bookmark_t_bookmark_id_fbe7b649_fk_bookmarks
        FOREIGN KEY (bookmark_id) REFERENCES bookmarks_bookmark(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT bookmarks_bookmark_tags_tag_id_6e32a767_fk_bookmarks_tag_id
        FOREIGN KEY (tag_id) REFERENCES bookmarks_tag(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookmarks_bookmark_tags_bookmark_id_fbe7b649 ON bookmarks_bookmark_tags USING btree (bookmark_id);
CREATE INDEX bookmarks_bookmark_tags_tag_id_6e32a767 ON bookmarks_bookmark_tags USING btree (tag_id);
