// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'linkding_api.dart';

RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
  if (T != dynamic &&
      requestOptions.responseType != ResponseType.bytes &&
      requestOptions.responseType != ResponseType.stream) {
    if (T == ResponseBody) {
      requestOptions.responseType = ResponseType.stream;
    } else if (T == String) {
      requestOptions.responseType = ResponseType.plain;
    } else {
      requestOptions.responseType = ResponseType.json;
    }
  }
  return requestOptions;
}

String _combineBaseUrls(String dioBaseUrl, String? baseUrl) {
  if (baseUrl == null || baseUrl.trim().isEmpty) {
    return dioBaseUrl;
  }
  final url = Uri.parse(baseUrl);
  if (url.isAbsolute) {
    return url.toString();
  }
  return Uri.parse(dioBaseUrl).resolveUri(url).toString();
}

Response<T> _buildResponse<T>(Response<dynamic> response, T data) {
  return Response<T>(
    data: data,
    headers: response.headers,
    isRedirect: response.isRedirect,
    redirects: response.redirects,
    requestOptions: response.requestOptions,
    statusCode: response.statusCode,
    statusMessage: response.statusMessage,
    extra: response.extra,
  );
}

final class _$LinkdingApi implements LinkdingApi {
  _$LinkdingApi(this._dio, {String? baseUrl}) : _baseUrl = baseUrl;

  final Dio _dio;
  final String? _baseUrl;

  @override
  Future<BookmarkPage> bookmarks({
    String? q,
    int? limit,
    int? offset,
    String? sort,
    String? modifiedSince,
    String? addedSince,
    int? bundle,
  }) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (q != null) _queryParameters['q'] = q;
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    if (sort != null) _queryParameters['sort'] = sort;
    if (modifiedSince != null) _queryParameters['modified_since'] = modifiedSince;
    if (addedSince != null) _queryParameters['added_since'] = addedSince;
    if (bundle != null) _queryParameters['bundle'] = bundle;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkPage>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkPage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<BookmarkPage> archivedBookmarks({
    String? q,
    int? limit,
    int? offset,
    String? sort,
    int? bundle,
  }) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (q != null) _queryParameters['q'] = q;
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    if (sort != null) _queryParameters['sort'] = sort;
    if (bundle != null) _queryParameters['bundle'] = bundle;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkPage>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/archived/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkPage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<BookmarkPage> sharedBookmarks({
    String? q,
    String? user,
    int? limit,
    int? offset,
  }) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (q != null) _queryParameters['q'] = q;
    if (user != null) _queryParameters['user'] = user;
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkPage>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/shared/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkPage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bookmark> bookmark(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bookmark>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bookmark.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<CheckResult> check(String url) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    _queryParameters['url'] = url;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<CheckResult>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/check/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return CheckResult.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bookmark> createBookmark(
    BookmarkInput input, {
    String? disableScraping,
  }) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (disableScraping != null) _queryParameters['disable_scraping'] = disableScraping;
    final Object? _data = input.toJson();
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bookmark>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bookmark.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bookmark> updateBookmark(int id, BookmarkInput input) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = input.toJson();
    final _options = Options(
      method: 'PUT',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bookmark>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bookmark.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bookmark> patchBookmark(int id, Map<String, Object?> changes) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = changes;
    final _options = Options(
      method: 'PATCH',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bookmark>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bookmark.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<void> archive(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/archive/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<void> unarchive(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/unarchive/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<void> deleteBookmark(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'DELETE',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<BookmarkAssetPage> assets(
    int bookmarkId, {
    int? limit,
    int? offset,
  }) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkAssetPage>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(bookmarkId.toString()) + '/assets/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkAssetPage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<BookmarkAsset> asset(int bookmarkId, int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkAsset>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(bookmarkId.toString()) + '/assets/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkAsset.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<BookmarkAsset> uploadAsset(int bookmarkId, MultipartFile file) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final _data = FormData.fromMap(<String, dynamic>{
      'file': file,
    });
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: 'multipart/form-data',
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BookmarkAsset>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(bookmarkId.toString()) + '/assets/upload/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BookmarkAsset.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<void> deleteAsset(int bookmarkId, int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'DELETE',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/bookmarks/' + Uri.encodeComponent(bookmarkId.toString()) + '/assets/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<TagPage> tags({int? limit, int? offset}) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<TagPage>(
        _options
            .compose(
              _dio.options,
              '/tags/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return TagPage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Tag> tag(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Tag>(
        _options
            .compose(
              _dio.options,
              '/tags/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Tag.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Tag> createTag(TagInput input) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = input.toJson();
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Tag>(
        _options
            .compose(
              _dio.options,
              '/tags/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Tag.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<void> deleteTag(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'DELETE',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/tags/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<BundlePage> bundles({int? limit, int? offset}) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    if (limit != null) _queryParameters['limit'] = limit;
    if (offset != null) _queryParameters['offset'] = offset;
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BundlePage>(
        _options
            .compose(
              _dio.options,
              '/bundles/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return BundlePage.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bundle> bundle(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bundle>(
        _options
            .compose(
              _dio.options,
              '/bundles/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bundle.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bundle> createBundle(BundleInput input) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = input.toJson();
    final _options = Options(
      method: 'POST',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bundle>(
        _options
            .compose(
              _dio.options,
              '/bundles/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bundle.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bundle> updateBundle(int id, BundleInput input) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = input.toJson();
    final _options = Options(
      method: 'PUT',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bundle>(
        _options
            .compose(
              _dio.options,
              '/bundles/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bundle.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<Bundle> patchBundle(int id, Map<String, Object?> changes) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = changes;
    final _options = Options(
      method: 'PATCH',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Bundle>(
        _options
            .compose(
              _dio.options,
              '/bundles/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return Bundle.fromJson(_result.data as Map<String, dynamic>);
  }

  @override
  Future<void> deleteBundle(int id) async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'DELETE',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    await _dio.fetch<void>(
      _setStreamType<void>(
        _options
            .compose(
              _dio.options,
              '/bundles/' + Uri.encodeComponent(id.toString()) + '/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return;
  }

  @override
  Future<UserProfile> profile() async {
    final _queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _extra = <String, dynamic>{};
    final Object? _data = null;
    final _options = Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
      contentType: null,
    );
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<UserProfile>(
        _options
            .compose(
              _dio.options,
              '/user/profile/',
              queryParameters: _queryParameters,
              data: _data,
              cancelToken: null,
              onSendProgress: null,
              onReceiveProgress: null,
            )
            .copyWith(
              baseUrl: _combineBaseUrls(
                _dio.options.baseUrl,
                _baseUrl,
              ),
            ),
      ),
    );
    return UserProfile.fromJson(_result.data as Map<String, dynamic>);
  }
}
